// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: J_C_UpdateFile.proto

package com.lxd.protobuf.msg.job.console;

public final class UpdateFile {
  private UpdateFile() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface UpdateFile_OrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 total_lump = 1;
    /**
     * <code>required int32 total_lump = 1;</code>
     *
     * <pre>
     *&#47;&lt; 数据总块数
     * </pre>
     */
    boolean hasTotalLump();
    /**
     * <code>required int32 total_lump = 1;</code>
     *
     * <pre>
     *&#47;&lt; 数据总块数
     * </pre>
     */
    int getTotalLump();

    // required int32 current_lump = 2;
    /**
     * <code>required int32 current_lump = 2;</code>
     *
     * <pre>
     *&#47;&lt; 当前书库块编号
     * </pre>
     */
    boolean hasCurrentLump();
    /**
     * <code>required int32 current_lump = 2;</code>
     *
     * <pre>
     *&#47;&lt; 当前书库块编号
     * </pre>
     */
    int getCurrentLump();

    // repeated .msg.job.console.Patch patch = 3;
    /**
     * <code>repeated .msg.job.console.Patch patch = 3;</code>
     *
     * <pre>
     *&#47;&lt; 补丁信息
     * </pre>
     */
    java.util.List<com.lxd.protobuf.msg.job.console.UpdateFile.Patch> 
        getPatchList();
    /**
     * <code>repeated .msg.job.console.Patch patch = 3;</code>
     *
     * <pre>
     *&#47;&lt; 补丁信息
     * </pre>
     */
    com.lxd.protobuf.msg.job.console.UpdateFile.Patch getPatch(int index);
    /**
     * <code>repeated .msg.job.console.Patch patch = 3;</code>
     *
     * <pre>
     *&#47;&lt; 补丁信息
     * </pre>
     */
    int getPatchCount();
    /**
     * <code>repeated .msg.job.console.Patch patch = 3;</code>
     *
     * <pre>
     *&#47;&lt; 补丁信息
     * </pre>
     */
    java.util.List<? extends com.lxd.protobuf.msg.job.console.UpdateFile.PatchOrBuilder> 
        getPatchOrBuilderList();
    /**
     * <code>repeated .msg.job.console.Patch patch = 3;</code>
     *
     * <pre>
     *&#47;&lt; 补丁信息
     * </pre>
     */
    com.lxd.protobuf.msg.job.console.UpdateFile.PatchOrBuilder getPatchOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code msg.job.console.UpdateFile_}
   */
  public static final class UpdateFile_ extends
      com.google.protobuf.GeneratedMessage
      implements UpdateFile_OrBuilder {
    // Use UpdateFile_.newBuilder() to construct.
    private UpdateFile_(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private UpdateFile_(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final UpdateFile_ defaultInstance;
    public static UpdateFile_ getDefaultInstance() {
      return defaultInstance;
    }

    public UpdateFile_ getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private UpdateFile_(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              totalLump_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              currentLump_ = input.readInt32();
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                patch_ = new java.util.ArrayList<com.lxd.protobuf.msg.job.console.UpdateFile.Patch>();
                mutable_bitField0_ |= 0x00000004;
              }
              patch_.add(input.readMessage(com.lxd.protobuf.msg.job.console.UpdateFile.Patch.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          patch_ = java.util.Collections.unmodifiableList(patch_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.lxd.protobuf.msg.job.console.UpdateFile.internal_static_msg_job_console_UpdateFile__descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lxd.protobuf.msg.job.console.UpdateFile.internal_static_msg_job_console_UpdateFile__fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.lxd.protobuf.msg.job.console.UpdateFile.UpdateFile_.class, com.lxd.protobuf.msg.job.console.UpdateFile.UpdateFile_.Builder.class);
    }

    public static com.google.protobuf.Parser<UpdateFile_> PARSER =
        new com.google.protobuf.AbstractParser<UpdateFile_>() {
      public UpdateFile_ parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new UpdateFile_(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<UpdateFile_> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 total_lump = 1;
    public static final int TOTAL_LUMP_FIELD_NUMBER = 1;
    private int totalLump_;
    /**
     * <code>required int32 total_lump = 1;</code>
     *
     * <pre>
     *&#47;&lt; 数据总块数
     * </pre>
     */
    public boolean hasTotalLump() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 total_lump = 1;</code>
     *
     * <pre>
     *&#47;&lt; 数据总块数
     * </pre>
     */
    public int getTotalLump() {
      return totalLump_;
    }

    // required int32 current_lump = 2;
    public static final int CURRENT_LUMP_FIELD_NUMBER = 2;
    private int currentLump_;
    /**
     * <code>required int32 current_lump = 2;</code>
     *
     * <pre>
     *&#47;&lt; 当前书库块编号
     * </pre>
     */
    public boolean hasCurrentLump() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 current_lump = 2;</code>
     *
     * <pre>
     *&#47;&lt; 当前书库块编号
     * </pre>
     */
    public int getCurrentLump() {
      return currentLump_;
    }

    // repeated .msg.job.console.Patch patch = 3;
    public static final int PATCH_FIELD_NUMBER = 3;
    private java.util.List<com.lxd.protobuf.msg.job.console.UpdateFile.Patch> patch_;
    /**
     * <code>repeated .msg.job.console.Patch patch = 3;</code>
     *
     * <pre>
     *&#47;&lt; 补丁信息
     * </pre>
     */
    public java.util.List<com.lxd.protobuf.msg.job.console.UpdateFile.Patch> getPatchList() {
      return patch_;
    }
    /**
     * <code>repeated .msg.job.console.Patch patch = 3;</code>
     *
     * <pre>
     *&#47;&lt; 补丁信息
     * </pre>
     */
    public java.util.List<? extends com.lxd.protobuf.msg.job.console.UpdateFile.PatchOrBuilder> 
        getPatchOrBuilderList() {
      return patch_;
    }
    /**
     * <code>repeated .msg.job.console.Patch patch = 3;</code>
     *
     * <pre>
     *&#47;&lt; 补丁信息
     * </pre>
     */
    public int getPatchCount() {
      return patch_.size();
    }
    /**
     * <code>repeated .msg.job.console.Patch patch = 3;</code>
     *
     * <pre>
     *&#47;&lt; 补丁信息
     * </pre>
     */
    public com.lxd.protobuf.msg.job.console.UpdateFile.Patch getPatch(int index) {
      return patch_.get(index);
    }
    /**
     * <code>repeated .msg.job.console.Patch patch = 3;</code>
     *
     * <pre>
     *&#47;&lt; 补丁信息
     * </pre>
     */
    public com.lxd.protobuf.msg.job.console.UpdateFile.PatchOrBuilder getPatchOrBuilder(
        int index) {
      return patch_.get(index);
    }

    private void initFields() {
      totalLump_ = 0;
      currentLump_ = 0;
      patch_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasTotalLump()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCurrentLump()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, totalLump_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, currentLump_);
      }
      for (int i = 0; i < patch_.size(); i++) {
        output.writeMessage(3, patch_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, totalLump_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, currentLump_);
      }
      for (int i = 0; i < patch_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, patch_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.lxd.protobuf.msg.job.console.UpdateFile.UpdateFile_ parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lxd.protobuf.msg.job.console.UpdateFile.UpdateFile_ parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lxd.protobuf.msg.job.console.UpdateFile.UpdateFile_ parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lxd.protobuf.msg.job.console.UpdateFile.UpdateFile_ parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lxd.protobuf.msg.job.console.UpdateFile.UpdateFile_ parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.lxd.protobuf.msg.job.console.UpdateFile.UpdateFile_ parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.lxd.protobuf.msg.job.console.UpdateFile.UpdateFile_ parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.lxd.protobuf.msg.job.console.UpdateFile.UpdateFile_ parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.lxd.protobuf.msg.job.console.UpdateFile.UpdateFile_ parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.lxd.protobuf.msg.job.console.UpdateFile.UpdateFile_ parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.lxd.protobuf.msg.job.console.UpdateFile.UpdateFile_ prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code msg.job.console.UpdateFile_}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.lxd.protobuf.msg.job.console.UpdateFile.UpdateFile_OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.lxd.protobuf.msg.job.console.UpdateFile.internal_static_msg_job_console_UpdateFile__descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.lxd.protobuf.msg.job.console.UpdateFile.internal_static_msg_job_console_UpdateFile__fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.lxd.protobuf.msg.job.console.UpdateFile.UpdateFile_.class, com.lxd.protobuf.msg.job.console.UpdateFile.UpdateFile_.Builder.class);
      }

      // Construct using com.lxd.protobuf.msg.job.console.UpdateFile.UpdateFile_.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getPatchFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        totalLump_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        currentLump_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        if (patchBuilder_ == null) {
          patch_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          patchBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.lxd.protobuf.msg.job.console.UpdateFile.internal_static_msg_job_console_UpdateFile__descriptor;
      }

      public com.lxd.protobuf.msg.job.console.UpdateFile.UpdateFile_ getDefaultInstanceForType() {
        return com.lxd.protobuf.msg.job.console.UpdateFile.UpdateFile_.getDefaultInstance();
      }

      public com.lxd.protobuf.msg.job.console.UpdateFile.UpdateFile_ build() {
        com.lxd.protobuf.msg.job.console.UpdateFile.UpdateFile_ result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.lxd.protobuf.msg.job.console.UpdateFile.UpdateFile_ buildPartial() {
        com.lxd.protobuf.msg.job.console.UpdateFile.UpdateFile_ result = new com.lxd.protobuf.msg.job.console.UpdateFile.UpdateFile_(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.totalLump_ = totalLump_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.currentLump_ = currentLump_;
        if (patchBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            patch_ = java.util.Collections.unmodifiableList(patch_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.patch_ = patch_;
        } else {
          result.patch_ = patchBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.lxd.protobuf.msg.job.console.UpdateFile.UpdateFile_) {
          return mergeFrom((com.lxd.protobuf.msg.job.console.UpdateFile.UpdateFile_)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.lxd.protobuf.msg.job.console.UpdateFile.UpdateFile_ other) {
        if (other == com.lxd.protobuf.msg.job.console.UpdateFile.UpdateFile_.getDefaultInstance()) return this;
        if (other.hasTotalLump()) {
          setTotalLump(other.getTotalLump());
        }
        if (other.hasCurrentLump()) {
          setCurrentLump(other.getCurrentLump());
        }
        if (patchBuilder_ == null) {
          if (!other.patch_.isEmpty()) {
            if (patch_.isEmpty()) {
              patch_ = other.patch_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensurePatchIsMutable();
              patch_.addAll(other.patch_);
            }
            onChanged();
          }
        } else {
          if (!other.patch_.isEmpty()) {
            if (patchBuilder_.isEmpty()) {
              patchBuilder_.dispose();
              patchBuilder_ = null;
              patch_ = other.patch_;
              bitField0_ = (bitField0_ & ~0x00000004);
              patchBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getPatchFieldBuilder() : null;
            } else {
              patchBuilder_.addAllMessages(other.patch_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasTotalLump()) {
          
          return false;
        }
        if (!hasCurrentLump()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.lxd.protobuf.msg.job.console.UpdateFile.UpdateFile_ parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.lxd.protobuf.msg.job.console.UpdateFile.UpdateFile_) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 total_lump = 1;
      private int totalLump_ ;
      /**
       * <code>required int32 total_lump = 1;</code>
       *
       * <pre>
       *&#47;&lt; 数据总块数
       * </pre>
       */
      public boolean hasTotalLump() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 total_lump = 1;</code>
       *
       * <pre>
       *&#47;&lt; 数据总块数
       * </pre>
       */
      public int getTotalLump() {
        return totalLump_;
      }
      /**
       * <code>required int32 total_lump = 1;</code>
       *
       * <pre>
       *&#47;&lt; 数据总块数
       * </pre>
       */
      public Builder setTotalLump(int value) {
        bitField0_ |= 0x00000001;
        totalLump_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 total_lump = 1;</code>
       *
       * <pre>
       *&#47;&lt; 数据总块数
       * </pre>
       */
      public Builder clearTotalLump() {
        bitField0_ = (bitField0_ & ~0x00000001);
        totalLump_ = 0;
        onChanged();
        return this;
      }

      // required int32 current_lump = 2;
      private int currentLump_ ;
      /**
       * <code>required int32 current_lump = 2;</code>
       *
       * <pre>
       *&#47;&lt; 当前书库块编号
       * </pre>
       */
      public boolean hasCurrentLump() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 current_lump = 2;</code>
       *
       * <pre>
       *&#47;&lt; 当前书库块编号
       * </pre>
       */
      public int getCurrentLump() {
        return currentLump_;
      }
      /**
       * <code>required int32 current_lump = 2;</code>
       *
       * <pre>
       *&#47;&lt; 当前书库块编号
       * </pre>
       */
      public Builder setCurrentLump(int value) {
        bitField0_ |= 0x00000002;
        currentLump_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 current_lump = 2;</code>
       *
       * <pre>
       *&#47;&lt; 当前书库块编号
       * </pre>
       */
      public Builder clearCurrentLump() {
        bitField0_ = (bitField0_ & ~0x00000002);
        currentLump_ = 0;
        onChanged();
        return this;
      }

      // repeated .msg.job.console.Patch patch = 3;
      private java.util.List<com.lxd.protobuf.msg.job.console.UpdateFile.Patch> patch_ =
        java.util.Collections.emptyList();
      private void ensurePatchIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          patch_ = new java.util.ArrayList<com.lxd.protobuf.msg.job.console.UpdateFile.Patch>(patch_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.lxd.protobuf.msg.job.console.UpdateFile.Patch, com.lxd.protobuf.msg.job.console.UpdateFile.Patch.Builder, com.lxd.protobuf.msg.job.console.UpdateFile.PatchOrBuilder> patchBuilder_;

      /**
       * <code>repeated .msg.job.console.Patch patch = 3;</code>
       *
       * <pre>
       *&#47;&lt; 补丁信息
       * </pre>
       */
      public java.util.List<com.lxd.protobuf.msg.job.console.UpdateFile.Patch> getPatchList() {
        if (patchBuilder_ == null) {
          return java.util.Collections.unmodifiableList(patch_);
        } else {
          return patchBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .msg.job.console.Patch patch = 3;</code>
       *
       * <pre>
       *&#47;&lt; 补丁信息
       * </pre>
       */
      public int getPatchCount() {
        if (patchBuilder_ == null) {
          return patch_.size();
        } else {
          return patchBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .msg.job.console.Patch patch = 3;</code>
       *
       * <pre>
       *&#47;&lt; 补丁信息
       * </pre>
       */
      public com.lxd.protobuf.msg.job.console.UpdateFile.Patch getPatch(int index) {
        if (patchBuilder_ == null) {
          return patch_.get(index);
        } else {
          return patchBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .msg.job.console.Patch patch = 3;</code>
       *
       * <pre>
       *&#47;&lt; 补丁信息
       * </pre>
       */
      public Builder setPatch(
          int index, com.lxd.protobuf.msg.job.console.UpdateFile.Patch value) {
        if (patchBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePatchIsMutable();
          patch_.set(index, value);
          onChanged();
        } else {
          patchBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .msg.job.console.Patch patch = 3;</code>
       *
       * <pre>
       *&#47;&lt; 补丁信息
       * </pre>
       */
      public Builder setPatch(
          int index, com.lxd.protobuf.msg.job.console.UpdateFile.Patch.Builder builderForValue) {
        if (patchBuilder_ == null) {
          ensurePatchIsMutable();
          patch_.set(index, builderForValue.build());
          onChanged();
        } else {
          patchBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .msg.job.console.Patch patch = 3;</code>
       *
       * <pre>
       *&#47;&lt; 补丁信息
       * </pre>
       */
      public Builder addPatch(com.lxd.protobuf.msg.job.console.UpdateFile.Patch value) {
        if (patchBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePatchIsMutable();
          patch_.add(value);
          onChanged();
        } else {
          patchBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .msg.job.console.Patch patch = 3;</code>
       *
       * <pre>
       *&#47;&lt; 补丁信息
       * </pre>
       */
      public Builder addPatch(
          int index, com.lxd.protobuf.msg.job.console.UpdateFile.Patch value) {
        if (patchBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePatchIsMutable();
          patch_.add(index, value);
          onChanged();
        } else {
          patchBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .msg.job.console.Patch patch = 3;</code>
       *
       * <pre>
       *&#47;&lt; 补丁信息
       * </pre>
       */
      public Builder addPatch(
          com.lxd.protobuf.msg.job.console.UpdateFile.Patch.Builder builderForValue) {
        if (patchBuilder_ == null) {
          ensurePatchIsMutable();
          patch_.add(builderForValue.build());
          onChanged();
        } else {
          patchBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .msg.job.console.Patch patch = 3;</code>
       *
       * <pre>
       *&#47;&lt; 补丁信息
       * </pre>
       */
      public Builder addPatch(
          int index, com.lxd.protobuf.msg.job.console.UpdateFile.Patch.Builder builderForValue) {
        if (patchBuilder_ == null) {
          ensurePatchIsMutable();
          patch_.add(index, builderForValue.build());
          onChanged();
        } else {
          patchBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .msg.job.console.Patch patch = 3;</code>
       *
       * <pre>
       *&#47;&lt; 补丁信息
       * </pre>
       */
      public Builder addAllPatch(
          java.lang.Iterable<? extends com.lxd.protobuf.msg.job.console.UpdateFile.Patch> values) {
        if (patchBuilder_ == null) {
          ensurePatchIsMutable();
          super.addAll(values, patch_);
          onChanged();
        } else {
          patchBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .msg.job.console.Patch patch = 3;</code>
       *
       * <pre>
       *&#47;&lt; 补丁信息
       * </pre>
       */
      public Builder clearPatch() {
        if (patchBuilder_ == null) {
          patch_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          patchBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .msg.job.console.Patch patch = 3;</code>
       *
       * <pre>
       *&#47;&lt; 补丁信息
       * </pre>
       */
      public Builder removePatch(int index) {
        if (patchBuilder_ == null) {
          ensurePatchIsMutable();
          patch_.remove(index);
          onChanged();
        } else {
          patchBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .msg.job.console.Patch patch = 3;</code>
       *
       * <pre>
       *&#47;&lt; 补丁信息
       * </pre>
       */
      public com.lxd.protobuf.msg.job.console.UpdateFile.Patch.Builder getPatchBuilder(
          int index) {
        return getPatchFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .msg.job.console.Patch patch = 3;</code>
       *
       * <pre>
       *&#47;&lt; 补丁信息
       * </pre>
       */
      public com.lxd.protobuf.msg.job.console.UpdateFile.PatchOrBuilder getPatchOrBuilder(
          int index) {
        if (patchBuilder_ == null) {
          return patch_.get(index);  } else {
          return patchBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .msg.job.console.Patch patch = 3;</code>
       *
       * <pre>
       *&#47;&lt; 补丁信息
       * </pre>
       */
      public java.util.List<? extends com.lxd.protobuf.msg.job.console.UpdateFile.PatchOrBuilder> 
           getPatchOrBuilderList() {
        if (patchBuilder_ != null) {
          return patchBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(patch_);
        }
      }
      /**
       * <code>repeated .msg.job.console.Patch patch = 3;</code>
       *
       * <pre>
       *&#47;&lt; 补丁信息
       * </pre>
       */
      public com.lxd.protobuf.msg.job.console.UpdateFile.Patch.Builder addPatchBuilder() {
        return getPatchFieldBuilder().addBuilder(
            com.lxd.protobuf.msg.job.console.UpdateFile.Patch.getDefaultInstance());
      }
      /**
       * <code>repeated .msg.job.console.Patch patch = 3;</code>
       *
       * <pre>
       *&#47;&lt; 补丁信息
       * </pre>
       */
      public com.lxd.protobuf.msg.job.console.UpdateFile.Patch.Builder addPatchBuilder(
          int index) {
        return getPatchFieldBuilder().addBuilder(
            index, com.lxd.protobuf.msg.job.console.UpdateFile.Patch.getDefaultInstance());
      }
      /**
       * <code>repeated .msg.job.console.Patch patch = 3;</code>
       *
       * <pre>
       *&#47;&lt; 补丁信息
       * </pre>
       */
      public java.util.List<com.lxd.protobuf.msg.job.console.UpdateFile.Patch.Builder> 
           getPatchBuilderList() {
        return getPatchFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.lxd.protobuf.msg.job.console.UpdateFile.Patch, com.lxd.protobuf.msg.job.console.UpdateFile.Patch.Builder, com.lxd.protobuf.msg.job.console.UpdateFile.PatchOrBuilder> 
          getPatchFieldBuilder() {
        if (patchBuilder_ == null) {
          patchBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.lxd.protobuf.msg.job.console.UpdateFile.Patch, com.lxd.protobuf.msg.job.console.UpdateFile.Patch.Builder, com.lxd.protobuf.msg.job.console.UpdateFile.PatchOrBuilder>(
                  patch_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          patch_ = null;
        }
        return patchBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:msg.job.console.UpdateFile_)
    }

    static {
      defaultInstance = new UpdateFile_(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:msg.job.console.UpdateFile_)
  }

  public interface PatchOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional bytes datas = 1;
    /**
     * <code>optional bytes datas = 1;</code>
     *
     * <pre>
     *&#47;&lt; 数据信息
     * </pre>
     */
    boolean hasDatas();
    /**
     * <code>optional bytes datas = 1;</code>
     *
     * <pre>
     *&#47;&lt; 数据信息
     * </pre>
     */
    com.google.protobuf.ByteString getDatas();

    // optional int64 info_id = 2;
    /**
     * <code>optional int64 info_id = 2;</code>
     *
     * <pre>
     *&#47;&lt; 块号
     * </pre>
     */
    boolean hasInfoId();
    /**
     * <code>optional int64 info_id = 2;</code>
     *
     * <pre>
     *&#47;&lt; 块号
     * </pre>
     */
    long getInfoId();
  }
  /**
   * Protobuf type {@code msg.job.console.Patch}
   */
  public static final class Patch extends
      com.google.protobuf.GeneratedMessage
      implements PatchOrBuilder {
    // Use Patch.newBuilder() to construct.
    private Patch(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Patch(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Patch defaultInstance;
    public static Patch getDefaultInstance() {
      return defaultInstance;
    }

    public Patch getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Patch(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              datas_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              infoId_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.lxd.protobuf.msg.job.console.UpdateFile.internal_static_msg_job_console_Patch_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lxd.protobuf.msg.job.console.UpdateFile.internal_static_msg_job_console_Patch_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.lxd.protobuf.msg.job.console.UpdateFile.Patch.class, com.lxd.protobuf.msg.job.console.UpdateFile.Patch.Builder.class);
    }

    public static com.google.protobuf.Parser<Patch> PARSER =
        new com.google.protobuf.AbstractParser<Patch>() {
      public Patch parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Patch(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Patch> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional bytes datas = 1;
    public static final int DATAS_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString datas_;
    /**
     * <code>optional bytes datas = 1;</code>
     *
     * <pre>
     *&#47;&lt; 数据信息
     * </pre>
     */
    public boolean hasDatas() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional bytes datas = 1;</code>
     *
     * <pre>
     *&#47;&lt; 数据信息
     * </pre>
     */
    public com.google.protobuf.ByteString getDatas() {
      return datas_;
    }

    // optional int64 info_id = 2;
    public static final int INFO_ID_FIELD_NUMBER = 2;
    private long infoId_;
    /**
     * <code>optional int64 info_id = 2;</code>
     *
     * <pre>
     *&#47;&lt; 块号
     * </pre>
     */
    public boolean hasInfoId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int64 info_id = 2;</code>
     *
     * <pre>
     *&#47;&lt; 块号
     * </pre>
     */
    public long getInfoId() {
      return infoId_;
    }

    private void initFields() {
      datas_ = com.google.protobuf.ByteString.EMPTY;
      infoId_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, datas_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, infoId_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, datas_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, infoId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.lxd.protobuf.msg.job.console.UpdateFile.Patch parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lxd.protobuf.msg.job.console.UpdateFile.Patch parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lxd.protobuf.msg.job.console.UpdateFile.Patch parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lxd.protobuf.msg.job.console.UpdateFile.Patch parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lxd.protobuf.msg.job.console.UpdateFile.Patch parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.lxd.protobuf.msg.job.console.UpdateFile.Patch parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.lxd.protobuf.msg.job.console.UpdateFile.Patch parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.lxd.protobuf.msg.job.console.UpdateFile.Patch parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.lxd.protobuf.msg.job.console.UpdateFile.Patch parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.lxd.protobuf.msg.job.console.UpdateFile.Patch parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.lxd.protobuf.msg.job.console.UpdateFile.Patch prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code msg.job.console.Patch}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.lxd.protobuf.msg.job.console.UpdateFile.PatchOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.lxd.protobuf.msg.job.console.UpdateFile.internal_static_msg_job_console_Patch_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.lxd.protobuf.msg.job.console.UpdateFile.internal_static_msg_job_console_Patch_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.lxd.protobuf.msg.job.console.UpdateFile.Patch.class, com.lxd.protobuf.msg.job.console.UpdateFile.Patch.Builder.class);
      }

      // Construct using com.lxd.protobuf.msg.job.console.UpdateFile.Patch.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        datas_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        infoId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.lxd.protobuf.msg.job.console.UpdateFile.internal_static_msg_job_console_Patch_descriptor;
      }

      public com.lxd.protobuf.msg.job.console.UpdateFile.Patch getDefaultInstanceForType() {
        return com.lxd.protobuf.msg.job.console.UpdateFile.Patch.getDefaultInstance();
      }

      public com.lxd.protobuf.msg.job.console.UpdateFile.Patch build() {
        com.lxd.protobuf.msg.job.console.UpdateFile.Patch result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.lxd.protobuf.msg.job.console.UpdateFile.Patch buildPartial() {
        com.lxd.protobuf.msg.job.console.UpdateFile.Patch result = new com.lxd.protobuf.msg.job.console.UpdateFile.Patch(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.datas_ = datas_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.infoId_ = infoId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.lxd.protobuf.msg.job.console.UpdateFile.Patch) {
          return mergeFrom((com.lxd.protobuf.msg.job.console.UpdateFile.Patch)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.lxd.protobuf.msg.job.console.UpdateFile.Patch other) {
        if (other == com.lxd.protobuf.msg.job.console.UpdateFile.Patch.getDefaultInstance()) return this;
        if (other.hasDatas()) {
          setDatas(other.getDatas());
        }
        if (other.hasInfoId()) {
          setInfoId(other.getInfoId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.lxd.protobuf.msg.job.console.UpdateFile.Patch parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.lxd.protobuf.msg.job.console.UpdateFile.Patch) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional bytes datas = 1;
      private com.google.protobuf.ByteString datas_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes datas = 1;</code>
       *
       * <pre>
       *&#47;&lt; 数据信息
       * </pre>
       */
      public boolean hasDatas() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional bytes datas = 1;</code>
       *
       * <pre>
       *&#47;&lt; 数据信息
       * </pre>
       */
      public com.google.protobuf.ByteString getDatas() {
        return datas_;
      }
      /**
       * <code>optional bytes datas = 1;</code>
       *
       * <pre>
       *&#47;&lt; 数据信息
       * </pre>
       */
      public Builder setDatas(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        datas_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes datas = 1;</code>
       *
       * <pre>
       *&#47;&lt; 数据信息
       * </pre>
       */
      public Builder clearDatas() {
        bitField0_ = (bitField0_ & ~0x00000001);
        datas_ = getDefaultInstance().getDatas();
        onChanged();
        return this;
      }

      // optional int64 info_id = 2;
      private long infoId_ ;
      /**
       * <code>optional int64 info_id = 2;</code>
       *
       * <pre>
       *&#47;&lt; 块号
       * </pre>
       */
      public boolean hasInfoId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int64 info_id = 2;</code>
       *
       * <pre>
       *&#47;&lt; 块号
       * </pre>
       */
      public long getInfoId() {
        return infoId_;
      }
      /**
       * <code>optional int64 info_id = 2;</code>
       *
       * <pre>
       *&#47;&lt; 块号
       * </pre>
       */
      public Builder setInfoId(long value) {
        bitField0_ |= 0x00000002;
        infoId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 info_id = 2;</code>
       *
       * <pre>
       *&#47;&lt; 块号
       * </pre>
       */
      public Builder clearInfoId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        infoId_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:msg.job.console.Patch)
    }

    static {
      defaultInstance = new Patch(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:msg.job.console.Patch)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_msg_job_console_UpdateFile__descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_msg_job_console_UpdateFile__fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_msg_job_console_Patch_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_msg_job_console_Patch_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024J_C_UpdateFile.proto\022\017msg.job.console\"" +
      "^\n\013UpdateFile_\022\022\n\ntotal_lump\030\001 \002(\005\022\024\n\014cu" +
      "rrent_lump\030\002 \002(\005\022%\n\005patch\030\003 \003(\0132\026.msg.jo" +
      "b.console.Patch\"\'\n\005Patch\022\r\n\005datas\030\001 \001(\014\022" +
      "\017\n\007info_id\030\002 \001(\003B.\n com.lxd.protobuf.msg" +
      ".job.consoleB\nUpdateFile"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_msg_job_console_UpdateFile__descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_msg_job_console_UpdateFile__fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_msg_job_console_UpdateFile__descriptor,
              new java.lang.String[] { "TotalLump", "CurrentLump", "Patch", });
          internal_static_msg_job_console_Patch_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_msg_job_console_Patch_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_msg_job_console_Patch_descriptor,
              new java.lang.String[] { "Datas", "InfoId", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
