// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Msg.proto

package com.lxd.protobuf.msg;

public final class Msg {
  private Msg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface Msg_OrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int64 job_id = 1;
    /**
     * <code>required int64 job_id = 1;</code>
     *
     * <pre>
     *&#47;&lt; 任务ID, 在其为-1时, 说明需要分配ID
     * </pre>
     */
    boolean hasJobId();
    /**
     * <code>required int64 job_id = 1;</code>
     *
     * <pre>
     *&#47;&lt; 任务ID, 在其为-1时, 说明需要分配ID
     * </pre>
     */
    long getJobId();

    // optional .msg.request.Request_ request = 2;
    /**
     * <code>optional .msg.request.Request_ request = 2;</code>
     *
     * <pre>
     *&#47;&lt; 请求
     * </pre>
     */
    boolean hasRequest();
    /**
     * <code>optional .msg.request.Request_ request = 2;</code>
     *
     * <pre>
     *&#47;&lt; 请求
     * </pre>
     */
    com.lxd.protobuf.msg.request.Request.Request_ getRequest();
    /**
     * <code>optional .msg.request.Request_ request = 2;</code>
     *
     * <pre>
     *&#47;&lt; 请求
     * </pre>
     */
    com.lxd.protobuf.msg.request.Request.Request_OrBuilder getRequestOrBuilder();

    // optional .msg.job.Job_ job = 3;
    /**
     * <code>optional .msg.job.Job_ job = 3;</code>
     *
     * <pre>
     *&#47;&lt; 任务
     * </pre>
     */
    boolean hasJob();
    /**
     * <code>optional .msg.job.Job_ job = 3;</code>
     *
     * <pre>
     *&#47;&lt; 任务
     * </pre>
     */
    com.lxd.protobuf.msg.job.Job.Job_ getJob();
    /**
     * <code>optional .msg.job.Job_ job = 3;</code>
     *
     * <pre>
     *&#47;&lt; 任务
     * </pre>
     */
    com.lxd.protobuf.msg.job.Job.Job_OrBuilder getJobOrBuilder();

    // optional .msg.result.Result_ result = 4;
    /**
     * <code>optional .msg.result.Result_ result = 4;</code>
     *
     * <pre>
     *&#47;&lt; 结果
     * </pre>
     */
    boolean hasResult();
    /**
     * <code>optional .msg.result.Result_ result = 4;</code>
     *
     * <pre>
     *&#47;&lt; 结果
     * </pre>
     */
    com.lxd.protobuf.msg.result.Result.Result_ getResult();
    /**
     * <code>optional .msg.result.Result_ result = 4;</code>
     *
     * <pre>
     *&#47;&lt; 结果
     * </pre>
     */
    com.lxd.protobuf.msg.result.Result.Result_OrBuilder getResultOrBuilder();
  }
  /**
   * Protobuf type {@code msg.Msg_}
   */
  public static final class Msg_ extends
      com.google.protobuf.GeneratedMessage
      implements Msg_OrBuilder {
    // Use Msg_.newBuilder() to construct.
    private Msg_(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Msg_(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Msg_ defaultInstance;
    public static Msg_ getDefaultInstance() {
      return defaultInstance;
    }

    public Msg_ getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Msg_(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              jobId_ = input.readInt64();
              break;
            }
            case 18: {
              com.lxd.protobuf.msg.request.Request.Request_.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = request_.toBuilder();
              }
              request_ = input.readMessage(com.lxd.protobuf.msg.request.Request.Request_.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(request_);
                request_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
            case 26: {
              com.lxd.protobuf.msg.job.Job.Job_.Builder subBuilder = null;
              if (((bitField0_ & 0x00000004) == 0x00000004)) {
                subBuilder = job_.toBuilder();
              }
              job_ = input.readMessage(com.lxd.protobuf.msg.job.Job.Job_.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(job_);
                job_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000004;
              break;
            }
            case 34: {
              com.lxd.protobuf.msg.result.Result.Result_.Builder subBuilder = null;
              if (((bitField0_ & 0x00000008) == 0x00000008)) {
                subBuilder = result_.toBuilder();
              }
              result_ = input.readMessage(com.lxd.protobuf.msg.result.Result.Result_.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(result_);
                result_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000008;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.lxd.protobuf.msg.Msg.internal_static_msg_Msg__descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lxd.protobuf.msg.Msg.internal_static_msg_Msg__fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.lxd.protobuf.msg.Msg.Msg_.class, com.lxd.protobuf.msg.Msg.Msg_.Builder.class);
    }

    public static com.google.protobuf.Parser<Msg_> PARSER =
        new com.google.protobuf.AbstractParser<Msg_>() {
      public Msg_ parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Msg_(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Msg_> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int64 job_id = 1;
    public static final int JOB_ID_FIELD_NUMBER = 1;
    private long jobId_;
    /**
     * <code>required int64 job_id = 1;</code>
     *
     * <pre>
     *&#47;&lt; 任务ID, 在其为-1时, 说明需要分配ID
     * </pre>
     */
    public boolean hasJobId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 job_id = 1;</code>
     *
     * <pre>
     *&#47;&lt; 任务ID, 在其为-1时, 说明需要分配ID
     * </pre>
     */
    public long getJobId() {
      return jobId_;
    }

    // optional .msg.request.Request_ request = 2;
    public static final int REQUEST_FIELD_NUMBER = 2;
    private com.lxd.protobuf.msg.request.Request.Request_ request_;
    /**
     * <code>optional .msg.request.Request_ request = 2;</code>
     *
     * <pre>
     *&#47;&lt; 请求
     * </pre>
     */
    public boolean hasRequest() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .msg.request.Request_ request = 2;</code>
     *
     * <pre>
     *&#47;&lt; 请求
     * </pre>
     */
    public com.lxd.protobuf.msg.request.Request.Request_ getRequest() {
      return request_;
    }
    /**
     * <code>optional .msg.request.Request_ request = 2;</code>
     *
     * <pre>
     *&#47;&lt; 请求
     * </pre>
     */
    public com.lxd.protobuf.msg.request.Request.Request_OrBuilder getRequestOrBuilder() {
      return request_;
    }

    // optional .msg.job.Job_ job = 3;
    public static final int JOB_FIELD_NUMBER = 3;
    private com.lxd.protobuf.msg.job.Job.Job_ job_;
    /**
     * <code>optional .msg.job.Job_ job = 3;</code>
     *
     * <pre>
     *&#47;&lt; 任务
     * </pre>
     */
    public boolean hasJob() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional .msg.job.Job_ job = 3;</code>
     *
     * <pre>
     *&#47;&lt; 任务
     * </pre>
     */
    public com.lxd.protobuf.msg.job.Job.Job_ getJob() {
      return job_;
    }
    /**
     * <code>optional .msg.job.Job_ job = 3;</code>
     *
     * <pre>
     *&#47;&lt; 任务
     * </pre>
     */
    public com.lxd.protobuf.msg.job.Job.Job_OrBuilder getJobOrBuilder() {
      return job_;
    }

    // optional .msg.result.Result_ result = 4;
    public static final int RESULT_FIELD_NUMBER = 4;
    private com.lxd.protobuf.msg.result.Result.Result_ result_;
    /**
     * <code>optional .msg.result.Result_ result = 4;</code>
     *
     * <pre>
     *&#47;&lt; 结果
     * </pre>
     */
    public boolean hasResult() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional .msg.result.Result_ result = 4;</code>
     *
     * <pre>
     *&#47;&lt; 结果
     * </pre>
     */
    public com.lxd.protobuf.msg.result.Result.Result_ getResult() {
      return result_;
    }
    /**
     * <code>optional .msg.result.Result_ result = 4;</code>
     *
     * <pre>
     *&#47;&lt; 结果
     * </pre>
     */
    public com.lxd.protobuf.msg.result.Result.Result_OrBuilder getResultOrBuilder() {
      return result_;
    }

    private void initFields() {
      jobId_ = 0L;
      request_ = com.lxd.protobuf.msg.request.Request.Request_.getDefaultInstance();
      job_ = com.lxd.protobuf.msg.job.Job.Job_.getDefaultInstance();
      result_ = com.lxd.protobuf.msg.result.Result.Result_.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasJobId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasRequest()) {
        if (!getRequest().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasJob()) {
        if (!getJob().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasResult()) {
        if (!getResult().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, jobId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, request_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(3, job_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeMessage(4, result_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, jobId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, request_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, job_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, result_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.lxd.protobuf.msg.Msg.Msg_ parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lxd.protobuf.msg.Msg.Msg_ parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lxd.protobuf.msg.Msg.Msg_ parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lxd.protobuf.msg.Msg.Msg_ parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lxd.protobuf.msg.Msg.Msg_ parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.lxd.protobuf.msg.Msg.Msg_ parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.lxd.protobuf.msg.Msg.Msg_ parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.lxd.protobuf.msg.Msg.Msg_ parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.lxd.protobuf.msg.Msg.Msg_ parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.lxd.protobuf.msg.Msg.Msg_ parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.lxd.protobuf.msg.Msg.Msg_ prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code msg.Msg_}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.lxd.protobuf.msg.Msg.Msg_OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.lxd.protobuf.msg.Msg.internal_static_msg_Msg__descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.lxd.protobuf.msg.Msg.internal_static_msg_Msg__fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.lxd.protobuf.msg.Msg.Msg_.class, com.lxd.protobuf.msg.Msg.Msg_.Builder.class);
      }

      // Construct using com.lxd.protobuf.msg.Msg.Msg_.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getRequestFieldBuilder();
          getJobFieldBuilder();
          getResultFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        jobId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (requestBuilder_ == null) {
          request_ = com.lxd.protobuf.msg.request.Request.Request_.getDefaultInstance();
        } else {
          requestBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        if (jobBuilder_ == null) {
          job_ = com.lxd.protobuf.msg.job.Job.Job_.getDefaultInstance();
        } else {
          jobBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        if (resultBuilder_ == null) {
          result_ = com.lxd.protobuf.msg.result.Result.Result_.getDefaultInstance();
        } else {
          resultBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.lxd.protobuf.msg.Msg.internal_static_msg_Msg__descriptor;
      }

      public com.lxd.protobuf.msg.Msg.Msg_ getDefaultInstanceForType() {
        return com.lxd.protobuf.msg.Msg.Msg_.getDefaultInstance();
      }

      public com.lxd.protobuf.msg.Msg.Msg_ build() {
        com.lxd.protobuf.msg.Msg.Msg_ result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.lxd.protobuf.msg.Msg.Msg_ buildPartial() {
        com.lxd.protobuf.msg.Msg.Msg_ result = new com.lxd.protobuf.msg.Msg.Msg_(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.jobId_ = jobId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (requestBuilder_ == null) {
          result.request_ = request_;
        } else {
          result.request_ = requestBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (jobBuilder_ == null) {
          result.job_ = job_;
        } else {
          result.job_ = jobBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        if (resultBuilder_ == null) {
          result.result_ = result_;
        } else {
          result.result_ = resultBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.lxd.protobuf.msg.Msg.Msg_) {
          return mergeFrom((com.lxd.protobuf.msg.Msg.Msg_)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.lxd.protobuf.msg.Msg.Msg_ other) {
        if (other == com.lxd.protobuf.msg.Msg.Msg_.getDefaultInstance()) return this;
        if (other.hasJobId()) {
          setJobId(other.getJobId());
        }
        if (other.hasRequest()) {
          mergeRequest(other.getRequest());
        }
        if (other.hasJob()) {
          mergeJob(other.getJob());
        }
        if (other.hasResult()) {
          mergeResult(other.getResult());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasJobId()) {
          
          return false;
        }
        if (hasRequest()) {
          if (!getRequest().isInitialized()) {
            
            return false;
          }
        }
        if (hasJob()) {
          if (!getJob().isInitialized()) {
            
            return false;
          }
        }
        if (hasResult()) {
          if (!getResult().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.lxd.protobuf.msg.Msg.Msg_ parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.lxd.protobuf.msg.Msg.Msg_) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int64 job_id = 1;
      private long jobId_ ;
      /**
       * <code>required int64 job_id = 1;</code>
       *
       * <pre>
       *&#47;&lt; 任务ID, 在其为-1时, 说明需要分配ID
       * </pre>
       */
      public boolean hasJobId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 job_id = 1;</code>
       *
       * <pre>
       *&#47;&lt; 任务ID, 在其为-1时, 说明需要分配ID
       * </pre>
       */
      public long getJobId() {
        return jobId_;
      }
      /**
       * <code>required int64 job_id = 1;</code>
       *
       * <pre>
       *&#47;&lt; 任务ID, 在其为-1时, 说明需要分配ID
       * </pre>
       */
      public Builder setJobId(long value) {
        bitField0_ |= 0x00000001;
        jobId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 job_id = 1;</code>
       *
       * <pre>
       *&#47;&lt; 任务ID, 在其为-1时, 说明需要分配ID
       * </pre>
       */
      public Builder clearJobId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        jobId_ = 0L;
        onChanged();
        return this;
      }

      // optional .msg.request.Request_ request = 2;
      private com.lxd.protobuf.msg.request.Request.Request_ request_ = com.lxd.protobuf.msg.request.Request.Request_.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.lxd.protobuf.msg.request.Request.Request_, com.lxd.protobuf.msg.request.Request.Request_.Builder, com.lxd.protobuf.msg.request.Request.Request_OrBuilder> requestBuilder_;
      /**
       * <code>optional .msg.request.Request_ request = 2;</code>
       *
       * <pre>
       *&#47;&lt; 请求
       * </pre>
       */
      public boolean hasRequest() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .msg.request.Request_ request = 2;</code>
       *
       * <pre>
       *&#47;&lt; 请求
       * </pre>
       */
      public com.lxd.protobuf.msg.request.Request.Request_ getRequest() {
        if (requestBuilder_ == null) {
          return request_;
        } else {
          return requestBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .msg.request.Request_ request = 2;</code>
       *
       * <pre>
       *&#47;&lt; 请求
       * </pre>
       */
      public Builder setRequest(com.lxd.protobuf.msg.request.Request.Request_ value) {
        if (requestBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          request_ = value;
          onChanged();
        } else {
          requestBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .msg.request.Request_ request = 2;</code>
       *
       * <pre>
       *&#47;&lt; 请求
       * </pre>
       */
      public Builder setRequest(
          com.lxd.protobuf.msg.request.Request.Request_.Builder builderForValue) {
        if (requestBuilder_ == null) {
          request_ = builderForValue.build();
          onChanged();
        } else {
          requestBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .msg.request.Request_ request = 2;</code>
       *
       * <pre>
       *&#47;&lt; 请求
       * </pre>
       */
      public Builder mergeRequest(com.lxd.protobuf.msg.request.Request.Request_ value) {
        if (requestBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              request_ != com.lxd.protobuf.msg.request.Request.Request_.getDefaultInstance()) {
            request_ =
              com.lxd.protobuf.msg.request.Request.Request_.newBuilder(request_).mergeFrom(value).buildPartial();
          } else {
            request_ = value;
          }
          onChanged();
        } else {
          requestBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .msg.request.Request_ request = 2;</code>
       *
       * <pre>
       *&#47;&lt; 请求
       * </pre>
       */
      public Builder clearRequest() {
        if (requestBuilder_ == null) {
          request_ = com.lxd.protobuf.msg.request.Request.Request_.getDefaultInstance();
          onChanged();
        } else {
          requestBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>optional .msg.request.Request_ request = 2;</code>
       *
       * <pre>
       *&#47;&lt; 请求
       * </pre>
       */
      public com.lxd.protobuf.msg.request.Request.Request_.Builder getRequestBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getRequestFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .msg.request.Request_ request = 2;</code>
       *
       * <pre>
       *&#47;&lt; 请求
       * </pre>
       */
      public com.lxd.protobuf.msg.request.Request.Request_OrBuilder getRequestOrBuilder() {
        if (requestBuilder_ != null) {
          return requestBuilder_.getMessageOrBuilder();
        } else {
          return request_;
        }
      }
      /**
       * <code>optional .msg.request.Request_ request = 2;</code>
       *
       * <pre>
       *&#47;&lt; 请求
       * </pre>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.lxd.protobuf.msg.request.Request.Request_, com.lxd.protobuf.msg.request.Request.Request_.Builder, com.lxd.protobuf.msg.request.Request.Request_OrBuilder> 
          getRequestFieldBuilder() {
        if (requestBuilder_ == null) {
          requestBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.lxd.protobuf.msg.request.Request.Request_, com.lxd.protobuf.msg.request.Request.Request_.Builder, com.lxd.protobuf.msg.request.Request.Request_OrBuilder>(
                  request_,
                  getParentForChildren(),
                  isClean());
          request_ = null;
        }
        return requestBuilder_;
      }

      // optional .msg.job.Job_ job = 3;
      private com.lxd.protobuf.msg.job.Job.Job_ job_ = com.lxd.protobuf.msg.job.Job.Job_.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.lxd.protobuf.msg.job.Job.Job_, com.lxd.protobuf.msg.job.Job.Job_.Builder, com.lxd.protobuf.msg.job.Job.Job_OrBuilder> jobBuilder_;
      /**
       * <code>optional .msg.job.Job_ job = 3;</code>
       *
       * <pre>
       *&#47;&lt; 任务
       * </pre>
       */
      public boolean hasJob() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional .msg.job.Job_ job = 3;</code>
       *
       * <pre>
       *&#47;&lt; 任务
       * </pre>
       */
      public com.lxd.protobuf.msg.job.Job.Job_ getJob() {
        if (jobBuilder_ == null) {
          return job_;
        } else {
          return jobBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .msg.job.Job_ job = 3;</code>
       *
       * <pre>
       *&#47;&lt; 任务
       * </pre>
       */
      public Builder setJob(com.lxd.protobuf.msg.job.Job.Job_ value) {
        if (jobBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          job_ = value;
          onChanged();
        } else {
          jobBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .msg.job.Job_ job = 3;</code>
       *
       * <pre>
       *&#47;&lt; 任务
       * </pre>
       */
      public Builder setJob(
          com.lxd.protobuf.msg.job.Job.Job_.Builder builderForValue) {
        if (jobBuilder_ == null) {
          job_ = builderForValue.build();
          onChanged();
        } else {
          jobBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .msg.job.Job_ job = 3;</code>
       *
       * <pre>
       *&#47;&lt; 任务
       * </pre>
       */
      public Builder mergeJob(com.lxd.protobuf.msg.job.Job.Job_ value) {
        if (jobBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              job_ != com.lxd.protobuf.msg.job.Job.Job_.getDefaultInstance()) {
            job_ =
              com.lxd.protobuf.msg.job.Job.Job_.newBuilder(job_).mergeFrom(value).buildPartial();
          } else {
            job_ = value;
          }
          onChanged();
        } else {
          jobBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .msg.job.Job_ job = 3;</code>
       *
       * <pre>
       *&#47;&lt; 任务
       * </pre>
       */
      public Builder clearJob() {
        if (jobBuilder_ == null) {
          job_ = com.lxd.protobuf.msg.job.Job.Job_.getDefaultInstance();
          onChanged();
        } else {
          jobBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      /**
       * <code>optional .msg.job.Job_ job = 3;</code>
       *
       * <pre>
       *&#47;&lt; 任务
       * </pre>
       */
      public com.lxd.protobuf.msg.job.Job.Job_.Builder getJobBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getJobFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .msg.job.Job_ job = 3;</code>
       *
       * <pre>
       *&#47;&lt; 任务
       * </pre>
       */
      public com.lxd.protobuf.msg.job.Job.Job_OrBuilder getJobOrBuilder() {
        if (jobBuilder_ != null) {
          return jobBuilder_.getMessageOrBuilder();
        } else {
          return job_;
        }
      }
      /**
       * <code>optional .msg.job.Job_ job = 3;</code>
       *
       * <pre>
       *&#47;&lt; 任务
       * </pre>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.lxd.protobuf.msg.job.Job.Job_, com.lxd.protobuf.msg.job.Job.Job_.Builder, com.lxd.protobuf.msg.job.Job.Job_OrBuilder> 
          getJobFieldBuilder() {
        if (jobBuilder_ == null) {
          jobBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.lxd.protobuf.msg.job.Job.Job_, com.lxd.protobuf.msg.job.Job.Job_.Builder, com.lxd.protobuf.msg.job.Job.Job_OrBuilder>(
                  job_,
                  getParentForChildren(),
                  isClean());
          job_ = null;
        }
        return jobBuilder_;
      }

      // optional .msg.result.Result_ result = 4;
      private com.lxd.protobuf.msg.result.Result.Result_ result_ = com.lxd.protobuf.msg.result.Result.Result_.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.lxd.protobuf.msg.result.Result.Result_, com.lxd.protobuf.msg.result.Result.Result_.Builder, com.lxd.protobuf.msg.result.Result.Result_OrBuilder> resultBuilder_;
      /**
       * <code>optional .msg.result.Result_ result = 4;</code>
       *
       * <pre>
       *&#47;&lt; 结果
       * </pre>
       */
      public boolean hasResult() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional .msg.result.Result_ result = 4;</code>
       *
       * <pre>
       *&#47;&lt; 结果
       * </pre>
       */
      public com.lxd.protobuf.msg.result.Result.Result_ getResult() {
        if (resultBuilder_ == null) {
          return result_;
        } else {
          return resultBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .msg.result.Result_ result = 4;</code>
       *
       * <pre>
       *&#47;&lt; 结果
       * </pre>
       */
      public Builder setResult(com.lxd.protobuf.msg.result.Result.Result_ value) {
        if (resultBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          result_ = value;
          onChanged();
        } else {
          resultBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .msg.result.Result_ result = 4;</code>
       *
       * <pre>
       *&#47;&lt; 结果
       * </pre>
       */
      public Builder setResult(
          com.lxd.protobuf.msg.result.Result.Result_.Builder builderForValue) {
        if (resultBuilder_ == null) {
          result_ = builderForValue.build();
          onChanged();
        } else {
          resultBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .msg.result.Result_ result = 4;</code>
       *
       * <pre>
       *&#47;&lt; 结果
       * </pre>
       */
      public Builder mergeResult(com.lxd.protobuf.msg.result.Result.Result_ value) {
        if (resultBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008) &&
              result_ != com.lxd.protobuf.msg.result.Result.Result_.getDefaultInstance()) {
            result_ =
              com.lxd.protobuf.msg.result.Result.Result_.newBuilder(result_).mergeFrom(value).buildPartial();
          } else {
            result_ = value;
          }
          onChanged();
        } else {
          resultBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .msg.result.Result_ result = 4;</code>
       *
       * <pre>
       *&#47;&lt; 结果
       * </pre>
       */
      public Builder clearResult() {
        if (resultBuilder_ == null) {
          result_ = com.lxd.protobuf.msg.result.Result.Result_.getDefaultInstance();
          onChanged();
        } else {
          resultBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      /**
       * <code>optional .msg.result.Result_ result = 4;</code>
       *
       * <pre>
       *&#47;&lt; 结果
       * </pre>
       */
      public com.lxd.protobuf.msg.result.Result.Result_.Builder getResultBuilder() {
        bitField0_ |= 0x00000008;
        onChanged();
        return getResultFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .msg.result.Result_ result = 4;</code>
       *
       * <pre>
       *&#47;&lt; 结果
       * </pre>
       */
      public com.lxd.protobuf.msg.result.Result.Result_OrBuilder getResultOrBuilder() {
        if (resultBuilder_ != null) {
          return resultBuilder_.getMessageOrBuilder();
        } else {
          return result_;
        }
      }
      /**
       * <code>optional .msg.result.Result_ result = 4;</code>
       *
       * <pre>
       *&#47;&lt; 结果
       * </pre>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.lxd.protobuf.msg.result.Result.Result_, com.lxd.protobuf.msg.result.Result.Result_.Builder, com.lxd.protobuf.msg.result.Result.Result_OrBuilder> 
          getResultFieldBuilder() {
        if (resultBuilder_ == null) {
          resultBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.lxd.protobuf.msg.result.Result.Result_, com.lxd.protobuf.msg.result.Result.Result_.Builder, com.lxd.protobuf.msg.result.Result.Result_OrBuilder>(
                  result_,
                  getParentForChildren(),
                  isClean());
          result_ = null;
        }
        return resultBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:msg.Msg_)
    }

    static {
      defaultInstance = new Msg_(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:msg.Msg_)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_msg_Msg__descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_msg_Msg__fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tMsg.proto\022\003msg\032\014Result.proto\032\tJob.prot" +
      "o\032\rRequest.proto\"\177\n\004Msg_\022\016\n\006job_id\030\001 \002(\003" +
      "\022&\n\007request\030\002 \001(\0132\025.msg.request.Request_" +
      "\022\032\n\003job\030\003 \001(\0132\r.msg.job.Job_\022#\n\006result\030\004" +
      " \001(\0132\023.msg.result.Result_B\033\n\024com.lxd.pro" +
      "tobuf.msgB\003Msg"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_msg_Msg__descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_msg_Msg__fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_msg_Msg__descriptor,
              new java.lang.String[] { "JobId", "Request", "Job", "Result", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.lxd.protobuf.msg.result.Result.getDescriptor(),
          com.lxd.protobuf.msg.job.Job.getDescriptor(),
          com.lxd.protobuf.msg.request.Request.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
