// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AddFileClientReq.proto

package com.lxd.protobuf.msg.req;

public final class AddFileClientReq {
  private AddFileClientReq() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface AddFileClientReq_OrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string md5 = 1;
    /**
     * <code>required string md5 = 1;</code>
     */
    boolean hasMd5();
    /**
     * <code>required string md5 = 1;</code>
     */
    java.lang.String getMd5();
    /**
     * <code>required string md5 = 1;</code>
     */
    com.google.protobuf.ByteString
        getMd5Bytes();

    // required int32 length = 2;
    /**
     * <code>required int32 length = 2;</code>
     */
    boolean hasLength();
    /**
     * <code>required int32 length = 2;</code>
     */
    int getLength();
  }
  /**
   * Protobuf type {@code req.AddFileClientReq_}
   */
  public static final class AddFileClientReq_ extends
      com.google.protobuf.GeneratedMessage
      implements AddFileClientReq_OrBuilder {
    // Use AddFileClientReq_.newBuilder() to construct.
    private AddFileClientReq_(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private AddFileClientReq_(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final AddFileClientReq_ defaultInstance;
    public static AddFileClientReq_ getDefaultInstance() {
      return defaultInstance;
    }

    public AddFileClientReq_ getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private AddFileClientReq_(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      @SuppressWarnings("unused")
    int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              md5_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              length_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.lxd.protobuf.msg.req.AddFileClientReq.internal_static_req_AddFileClientReq__descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lxd.protobuf.msg.req.AddFileClientReq.internal_static_req_AddFileClientReq__fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.lxd.protobuf.msg.req.AddFileClientReq.AddFileClientReq_.class, com.lxd.protobuf.msg.req.AddFileClientReq.AddFileClientReq_.Builder.class);
    }

    public static com.google.protobuf.Parser<AddFileClientReq_> PARSER =
        new com.google.protobuf.AbstractParser<AddFileClientReq_>() {
      public AddFileClientReq_ parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AddFileClientReq_(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<AddFileClientReq_> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string md5 = 1;
    public static final int MD5_FIELD_NUMBER = 1;
    private java.lang.Object md5_;
    /**
     * <code>required string md5 = 1;</code>
     */
    public boolean hasMd5() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string md5 = 1;</code>
     */
    public java.lang.String getMd5() {
      java.lang.Object ref = md5_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          md5_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string md5 = 1;</code>
     */
    public com.google.protobuf.ByteString
        getMd5Bytes() {
      java.lang.Object ref = md5_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        md5_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required int32 length = 2;
    public static final int LENGTH_FIELD_NUMBER = 2;
    private int length_;
    /**
     * <code>required int32 length = 2;</code>
     */
    public boolean hasLength() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 length = 2;</code>
     */
    public int getLength() {
      return length_;
    }

    private void initFields() {
      md5_ = "";
      length_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasMd5()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLength()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getMd5Bytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, length_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getMd5Bytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, length_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.lxd.protobuf.msg.req.AddFileClientReq.AddFileClientReq_ parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lxd.protobuf.msg.req.AddFileClientReq.AddFileClientReq_ parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lxd.protobuf.msg.req.AddFileClientReq.AddFileClientReq_ parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lxd.protobuf.msg.req.AddFileClientReq.AddFileClientReq_ parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lxd.protobuf.msg.req.AddFileClientReq.AddFileClientReq_ parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.lxd.protobuf.msg.req.AddFileClientReq.AddFileClientReq_ parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.lxd.protobuf.msg.req.AddFileClientReq.AddFileClientReq_ parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.lxd.protobuf.msg.req.AddFileClientReq.AddFileClientReq_ parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.lxd.protobuf.msg.req.AddFileClientReq.AddFileClientReq_ parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.lxd.protobuf.msg.req.AddFileClientReq.AddFileClientReq_ parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.lxd.protobuf.msg.req.AddFileClientReq.AddFileClientReq_ prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code req.AddFileClientReq_}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.lxd.protobuf.msg.req.AddFileClientReq.AddFileClientReq_OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.lxd.protobuf.msg.req.AddFileClientReq.internal_static_req_AddFileClientReq__descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.lxd.protobuf.msg.req.AddFileClientReq.internal_static_req_AddFileClientReq__fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.lxd.protobuf.msg.req.AddFileClientReq.AddFileClientReq_.class, com.lxd.protobuf.msg.req.AddFileClientReq.AddFileClientReq_.Builder.class);
      }

      // Construct using com.lxd.protobuf.msg.req.AddFileClientReq.AddFileClientReq_.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        md5_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        length_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.lxd.protobuf.msg.req.AddFileClientReq.internal_static_req_AddFileClientReq__descriptor;
      }

      public com.lxd.protobuf.msg.req.AddFileClientReq.AddFileClientReq_ getDefaultInstanceForType() {
        return com.lxd.protobuf.msg.req.AddFileClientReq.AddFileClientReq_.getDefaultInstance();
      }

      public com.lxd.protobuf.msg.req.AddFileClientReq.AddFileClientReq_ build() {
        com.lxd.protobuf.msg.req.AddFileClientReq.AddFileClientReq_ result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.lxd.protobuf.msg.req.AddFileClientReq.AddFileClientReq_ buildPartial() {
        com.lxd.protobuf.msg.req.AddFileClientReq.AddFileClientReq_ result = new com.lxd.protobuf.msg.req.AddFileClientReq.AddFileClientReq_(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.md5_ = md5_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.length_ = length_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.lxd.protobuf.msg.req.AddFileClientReq.AddFileClientReq_) {
          return mergeFrom((com.lxd.protobuf.msg.req.AddFileClientReq.AddFileClientReq_)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.lxd.protobuf.msg.req.AddFileClientReq.AddFileClientReq_ other) {
        if (other == com.lxd.protobuf.msg.req.AddFileClientReq.AddFileClientReq_.getDefaultInstance()) return this;
        if (other.hasMd5()) {
          bitField0_ |= 0x00000001;
          md5_ = other.md5_;
          onChanged();
        }
        if (other.hasLength()) {
          setLength(other.getLength());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasMd5()) {
          
          return false;
        }
        if (!hasLength()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.lxd.protobuf.msg.req.AddFileClientReq.AddFileClientReq_ parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.lxd.protobuf.msg.req.AddFileClientReq.AddFileClientReq_) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string md5 = 1;
      private java.lang.Object md5_ = "";
      /**
       * <code>required string md5 = 1;</code>
       */
      public boolean hasMd5() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string md5 = 1;</code>
       */
      public java.lang.String getMd5() {
        java.lang.Object ref = md5_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          md5_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string md5 = 1;</code>
       */
      public com.google.protobuf.ByteString
          getMd5Bytes() {
        java.lang.Object ref = md5_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          md5_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string md5 = 1;</code>
       */
      public Builder setMd5(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        md5_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string md5 = 1;</code>
       */
      public Builder clearMd5() {
        bitField0_ = (bitField0_ & ~0x00000001);
        md5_ = getDefaultInstance().getMd5();
        onChanged();
        return this;
      }
      /**
       * <code>required string md5 = 1;</code>
       */
      public Builder setMd5Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        md5_ = value;
        onChanged();
        return this;
      }

      // required int32 length = 2;
      private int length_ ;
      /**
       * <code>required int32 length = 2;</code>
       */
      public boolean hasLength() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 length = 2;</code>
       */
      public int getLength() {
        return length_;
      }
      /**
       * <code>required int32 length = 2;</code>
       */
      public Builder setLength(int value) {
        bitField0_ |= 0x00000002;
        length_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 length = 2;</code>
       */
      public Builder clearLength() {
        bitField0_ = (bitField0_ & ~0x00000002);
        length_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:req.AddFileClientReq_)
    }

    static {
      defaultInstance = new AddFileClientReq_(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:req.AddFileClientReq_)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_req_AddFileClientReq__descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_req_AddFileClientReq__fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026AddFileClientReq.proto\022\003req\"0\n\021AddFile" +
      "ClientReq_\022\013\n\003md5\030\001 \002(\t\022\016\n\006length\030\002 \002(\005B" +
      ",\n\030com.lxd.protobuf.msg.reqB\020AddFileClie" +
      "ntReq"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_req_AddFileClientReq__descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_req_AddFileClientReq__fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_req_AddFileClientReq__descriptor,
              new java.lang.String[] { "Md5", "Length", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
