// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AddFileServerResp.proto

package com.lxd.protobuf.msg.resp;

public final class AddFileServerResp {
  private AddFileServerResp() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface AddFileServerResp_OrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .AddFileServerResp_.Result result = 1;
    /**
     * <code>required .AddFileServerResp_.Result result = 1;</code>
     */
    boolean hasResult();
    /**
     * <code>required .AddFileServerResp_.Result result = 1;</code>
     */
    com.lxd.protobuf.msg.resp.AddFileServerResp.AddFileServerResp_.Result getResult();

    // optional string error_msg = 2;
    /**
     * <code>optional string error_msg = 2;</code>
     */
    boolean hasErrorMsg();
    /**
     * <code>optional string error_msg = 2;</code>
     */
    java.lang.String getErrorMsg();
    /**
     * <code>optional string error_msg = 2;</code>
     */
    com.google.protobuf.ByteString
        getErrorMsgBytes();
  }
  /**
   * Protobuf type {@code AddFileServerResp_}
   */
  public static final class AddFileServerResp_ extends
      com.google.protobuf.GeneratedMessage
      implements AddFileServerResp_OrBuilder {
    // Use AddFileServerResp_.newBuilder() to construct.
    private AddFileServerResp_(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private AddFileServerResp_(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final AddFileServerResp_ defaultInstance;
    public static AddFileServerResp_ getDefaultInstance() {
      return defaultInstance;
    }

    public AddFileServerResp_ getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private AddFileServerResp_(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      @SuppressWarnings("unused")
    int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.lxd.protobuf.msg.resp.AddFileServerResp.AddFileServerResp_.Result value = com.lxd.protobuf.msg.resp.AddFileServerResp.AddFileServerResp_.Result.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                result_ = value;
              }
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              errorMsg_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.lxd.protobuf.msg.resp.AddFileServerResp.internal_static_AddFileServerResp__descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lxd.protobuf.msg.resp.AddFileServerResp.internal_static_AddFileServerResp__fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.lxd.protobuf.msg.resp.AddFileServerResp.AddFileServerResp_.class, com.lxd.protobuf.msg.resp.AddFileServerResp.AddFileServerResp_.Builder.class);
    }

    public static com.google.protobuf.Parser<AddFileServerResp_> PARSER =
        new com.google.protobuf.AbstractParser<AddFileServerResp_>() {
      public AddFileServerResp_ parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AddFileServerResp_(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<AddFileServerResp_> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code AddFileServerResp_.Result}
     */
    public enum Result
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>OK = 0;</code>
       */
      OK(0, 0),
      /**
       * <code>ERROR = 1;</code>
       */
      ERROR(1, 1),
      ;

      /**
       * <code>OK = 0;</code>
       */
      public static final int OK_VALUE = 0;
      /**
       * <code>ERROR = 1;</code>
       */
      public static final int ERROR_VALUE = 1;


      public final int getNumber() { return value; }

      public static Result valueOf(int value) {
        switch (value) {
          case 0: return OK;
          case 1: return ERROR;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Result>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Result>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Result>() {
              public Result findValueByNumber(int number) {
                return Result.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.lxd.protobuf.msg.resp.AddFileServerResp.AddFileServerResp_.getDescriptor().getEnumTypes().get(0);
      }

      private static final Result[] VALUES = values();

      public static Result valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private Result(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:AddFileServerResp_.Result)
    }

    private int bitField0_;
    // required .AddFileServerResp_.Result result = 1;
    public static final int RESULT_FIELD_NUMBER = 1;
    private com.lxd.protobuf.msg.resp.AddFileServerResp.AddFileServerResp_.Result result_;
    /**
     * <code>required .AddFileServerResp_.Result result = 1;</code>
     */
    public boolean hasResult() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .AddFileServerResp_.Result result = 1;</code>
     */
    public com.lxd.protobuf.msg.resp.AddFileServerResp.AddFileServerResp_.Result getResult() {
      return result_;
    }

    // optional string error_msg = 2;
    public static final int ERROR_MSG_FIELD_NUMBER = 2;
    private java.lang.Object errorMsg_;
    /**
     * <code>optional string error_msg = 2;</code>
     */
    public boolean hasErrorMsg() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string error_msg = 2;</code>
     */
    public java.lang.String getErrorMsg() {
      java.lang.Object ref = errorMsg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          errorMsg_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string error_msg = 2;</code>
     */
    public com.google.protobuf.ByteString
        getErrorMsgBytes() {
      java.lang.Object ref = errorMsg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        errorMsg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      result_ = com.lxd.protobuf.msg.resp.AddFileServerResp.AddFileServerResp_.Result.OK;
      errorMsg_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasResult()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, result_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getErrorMsgBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, result_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getErrorMsgBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.lxd.protobuf.msg.resp.AddFileServerResp.AddFileServerResp_ parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lxd.protobuf.msg.resp.AddFileServerResp.AddFileServerResp_ parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lxd.protobuf.msg.resp.AddFileServerResp.AddFileServerResp_ parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lxd.protobuf.msg.resp.AddFileServerResp.AddFileServerResp_ parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lxd.protobuf.msg.resp.AddFileServerResp.AddFileServerResp_ parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.lxd.protobuf.msg.resp.AddFileServerResp.AddFileServerResp_ parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.lxd.protobuf.msg.resp.AddFileServerResp.AddFileServerResp_ parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.lxd.protobuf.msg.resp.AddFileServerResp.AddFileServerResp_ parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.lxd.protobuf.msg.resp.AddFileServerResp.AddFileServerResp_ parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.lxd.protobuf.msg.resp.AddFileServerResp.AddFileServerResp_ parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.lxd.protobuf.msg.resp.AddFileServerResp.AddFileServerResp_ prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code AddFileServerResp_}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.lxd.protobuf.msg.resp.AddFileServerResp.AddFileServerResp_OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.lxd.protobuf.msg.resp.AddFileServerResp.internal_static_AddFileServerResp__descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.lxd.protobuf.msg.resp.AddFileServerResp.internal_static_AddFileServerResp__fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.lxd.protobuf.msg.resp.AddFileServerResp.AddFileServerResp_.class, com.lxd.protobuf.msg.resp.AddFileServerResp.AddFileServerResp_.Builder.class);
      }

      // Construct using com.lxd.protobuf.msg.resp.AddFileServerResp.AddFileServerResp_.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        result_ = com.lxd.protobuf.msg.resp.AddFileServerResp.AddFileServerResp_.Result.OK;
        bitField0_ = (bitField0_ & ~0x00000001);
        errorMsg_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.lxd.protobuf.msg.resp.AddFileServerResp.internal_static_AddFileServerResp__descriptor;
      }

      public com.lxd.protobuf.msg.resp.AddFileServerResp.AddFileServerResp_ getDefaultInstanceForType() {
        return com.lxd.protobuf.msg.resp.AddFileServerResp.AddFileServerResp_.getDefaultInstance();
      }

      public com.lxd.protobuf.msg.resp.AddFileServerResp.AddFileServerResp_ build() {
        com.lxd.protobuf.msg.resp.AddFileServerResp.AddFileServerResp_ result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.lxd.protobuf.msg.resp.AddFileServerResp.AddFileServerResp_ buildPartial() {
        com.lxd.protobuf.msg.resp.AddFileServerResp.AddFileServerResp_ result = new com.lxd.protobuf.msg.resp.AddFileServerResp.AddFileServerResp_(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.result_ = result_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.errorMsg_ = errorMsg_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.lxd.protobuf.msg.resp.AddFileServerResp.AddFileServerResp_) {
          return mergeFrom((com.lxd.protobuf.msg.resp.AddFileServerResp.AddFileServerResp_)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.lxd.protobuf.msg.resp.AddFileServerResp.AddFileServerResp_ other) {
        if (other == com.lxd.protobuf.msg.resp.AddFileServerResp.AddFileServerResp_.getDefaultInstance()) return this;
        if (other.hasResult()) {
          setResult(other.getResult());
        }
        if (other.hasErrorMsg()) {
          bitField0_ |= 0x00000002;
          errorMsg_ = other.errorMsg_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasResult()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.lxd.protobuf.msg.resp.AddFileServerResp.AddFileServerResp_ parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.lxd.protobuf.msg.resp.AddFileServerResp.AddFileServerResp_) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .AddFileServerResp_.Result result = 1;
      private com.lxd.protobuf.msg.resp.AddFileServerResp.AddFileServerResp_.Result result_ = com.lxd.protobuf.msg.resp.AddFileServerResp.AddFileServerResp_.Result.OK;
      /**
       * <code>required .AddFileServerResp_.Result result = 1;</code>
       */
      public boolean hasResult() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .AddFileServerResp_.Result result = 1;</code>
       */
      public com.lxd.protobuf.msg.resp.AddFileServerResp.AddFileServerResp_.Result getResult() {
        return result_;
      }
      /**
       * <code>required .AddFileServerResp_.Result result = 1;</code>
       */
      public Builder setResult(com.lxd.protobuf.msg.resp.AddFileServerResp.AddFileServerResp_.Result value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        result_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .AddFileServerResp_.Result result = 1;</code>
       */
      public Builder clearResult() {
        bitField0_ = (bitField0_ & ~0x00000001);
        result_ = com.lxd.protobuf.msg.resp.AddFileServerResp.AddFileServerResp_.Result.OK;
        onChanged();
        return this;
      }

      // optional string error_msg = 2;
      private java.lang.Object errorMsg_ = "";
      /**
       * <code>optional string error_msg = 2;</code>
       */
      public boolean hasErrorMsg() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string error_msg = 2;</code>
       */
      public java.lang.String getErrorMsg() {
        java.lang.Object ref = errorMsg_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          errorMsg_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string error_msg = 2;</code>
       */
      public com.google.protobuf.ByteString
          getErrorMsgBytes() {
        java.lang.Object ref = errorMsg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          errorMsg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string error_msg = 2;</code>
       */
      public Builder setErrorMsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        errorMsg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string error_msg = 2;</code>
       */
      public Builder clearErrorMsg() {
        bitField0_ = (bitField0_ & ~0x00000002);
        errorMsg_ = getDefaultInstance().getErrorMsg();
        onChanged();
        return this;
      }
      /**
       * <code>optional string error_msg = 2;</code>
       */
      public Builder setErrorMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        errorMsg_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:AddFileServerResp_)
    }

    static {
      defaultInstance = new AddFileServerResp_(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:AddFileServerResp_)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_AddFileServerResp__descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_AddFileServerResp__fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027AddFileServerResp.proto\"p\n\022AddFileServ" +
      "erResp_\022*\n\006result\030\001 \002(\0162\032.AddFileServerR" +
      "esp_.Result\022\021\n\terror_msg\030\002 \001(\t\"\033\n\006Result" +
      "\022\006\n\002OK\020\000\022\t\n\005ERROR\020\001B.\n\031com.lxd.protobuf." +
      "msg.respB\021AddFileServerResp"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_AddFileServerResp__descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_AddFileServerResp__fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_AddFileServerResp__descriptor,
              new java.lang.String[] { "Result", "ErrorMsg", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
