// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AddFileClientResp.proto

package com.lxd.protobuf.msg.resp;

public final class AddFileClientResp {
  private AddFileClientResp() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface AddFileClientResp_OrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 id = 1;
    /**
     * <code>required int32 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required int32 id = 1;</code>
     */
    int getId();

    // required int32 total_block = 2;
    /**
     * <code>required int32 total_block = 2;</code>
     */
    boolean hasTotalBlock();
    /**
     * <code>required int32 total_block = 2;</code>
     */
    int getTotalBlock();

    // required int32 current_block = 3;
    /**
     * <code>required int32 current_block = 3;</code>
     */
    boolean hasCurrentBlock();
    /**
     * <code>required int32 current_block = 3;</code>
     */
    int getCurrentBlock();

    // repeated bytes datas = 4;
    /**
     * <code>repeated bytes datas = 4;</code>
     */
    java.util.List<com.google.protobuf.ByteString> getDatasList();
    /**
     * <code>repeated bytes datas = 4;</code>
     */
    int getDatasCount();
    /**
     * <code>repeated bytes datas = 4;</code>
     */
    com.google.protobuf.ByteString getDatas(int index);
  }
  /**
   * Protobuf type {@code AddFileClientResp_}
   */
  public static final class AddFileClientResp_ extends
      com.google.protobuf.GeneratedMessage
      implements AddFileClientResp_OrBuilder {
    // Use AddFileClientResp_.newBuilder() to construct.
    private AddFileClientResp_(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private AddFileClientResp_(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final AddFileClientResp_ defaultInstance;
    public static AddFileClientResp_ getDefaultInstance() {
      return defaultInstance;
    }

    public AddFileClientResp_ getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private AddFileClientResp_(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              totalBlock_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              currentBlock_ = input.readInt32();
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                datas_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
                mutable_bitField0_ |= 0x00000008;
              }
              datas_.add(input.readBytes());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          datas_ = java.util.Collections.unmodifiableList(datas_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.lxd.protobuf.msg.resp.AddFileClientResp.internal_static_AddFileClientResp__descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lxd.protobuf.msg.resp.AddFileClientResp.internal_static_AddFileClientResp__fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.lxd.protobuf.msg.resp.AddFileClientResp.AddFileClientResp_.class, com.lxd.protobuf.msg.resp.AddFileClientResp.AddFileClientResp_.Builder.class);
    }

    public static com.google.protobuf.Parser<AddFileClientResp_> PARSER =
        new com.google.protobuf.AbstractParser<AddFileClientResp_>() {
      public AddFileClientResp_ parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AddFileClientResp_(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<AddFileClientResp_> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>required int32 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    // required int32 total_block = 2;
    public static final int TOTAL_BLOCK_FIELD_NUMBER = 2;
    private int totalBlock_;
    /**
     * <code>required int32 total_block = 2;</code>
     */
    public boolean hasTotalBlock() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 total_block = 2;</code>
     */
    public int getTotalBlock() {
      return totalBlock_;
    }

    // required int32 current_block = 3;
    public static final int CURRENT_BLOCK_FIELD_NUMBER = 3;
    private int currentBlock_;
    /**
     * <code>required int32 current_block = 3;</code>
     */
    public boolean hasCurrentBlock() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 current_block = 3;</code>
     */
    public int getCurrentBlock() {
      return currentBlock_;
    }

    // repeated bytes datas = 4;
    public static final int DATAS_FIELD_NUMBER = 4;
    private java.util.List<com.google.protobuf.ByteString> datas_;
    /**
     * <code>repeated bytes datas = 4;</code>
     */
    public java.util.List<com.google.protobuf.ByteString>
        getDatasList() {
      return datas_;
    }
    /**
     * <code>repeated bytes datas = 4;</code>
     */
    public int getDatasCount() {
      return datas_.size();
    }
    /**
     * <code>repeated bytes datas = 4;</code>
     */
    public com.google.protobuf.ByteString getDatas(int index) {
      return datas_.get(index);
    }

    private void initFields() {
      id_ = 0;
      totalBlock_ = 0;
      currentBlock_ = 0;
      datas_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTotalBlock()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCurrentBlock()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, totalBlock_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, currentBlock_);
      }
      for (int i = 0; i < datas_.size(); i++) {
        output.writeBytes(4, datas_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, totalBlock_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, currentBlock_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < datas_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(datas_.get(i));
        }
        size += dataSize;
        size += 1 * getDatasList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.lxd.protobuf.msg.resp.AddFileClientResp.AddFileClientResp_ parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lxd.protobuf.msg.resp.AddFileClientResp.AddFileClientResp_ parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lxd.protobuf.msg.resp.AddFileClientResp.AddFileClientResp_ parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lxd.protobuf.msg.resp.AddFileClientResp.AddFileClientResp_ parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lxd.protobuf.msg.resp.AddFileClientResp.AddFileClientResp_ parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.lxd.protobuf.msg.resp.AddFileClientResp.AddFileClientResp_ parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.lxd.protobuf.msg.resp.AddFileClientResp.AddFileClientResp_ parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.lxd.protobuf.msg.resp.AddFileClientResp.AddFileClientResp_ parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.lxd.protobuf.msg.resp.AddFileClientResp.AddFileClientResp_ parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.lxd.protobuf.msg.resp.AddFileClientResp.AddFileClientResp_ parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.lxd.protobuf.msg.resp.AddFileClientResp.AddFileClientResp_ prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code AddFileClientResp_}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.lxd.protobuf.msg.resp.AddFileClientResp.AddFileClientResp_OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.lxd.protobuf.msg.resp.AddFileClientResp.internal_static_AddFileClientResp__descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.lxd.protobuf.msg.resp.AddFileClientResp.internal_static_AddFileClientResp__fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.lxd.protobuf.msg.resp.AddFileClientResp.AddFileClientResp_.class, com.lxd.protobuf.msg.resp.AddFileClientResp.AddFileClientResp_.Builder.class);
      }

      // Construct using com.lxd.protobuf.msg.resp.AddFileClientResp.AddFileClientResp_.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        totalBlock_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        currentBlock_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        datas_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.lxd.protobuf.msg.resp.AddFileClientResp.internal_static_AddFileClientResp__descriptor;
      }

      public com.lxd.protobuf.msg.resp.AddFileClientResp.AddFileClientResp_ getDefaultInstanceForType() {
        return com.lxd.protobuf.msg.resp.AddFileClientResp.AddFileClientResp_.getDefaultInstance();
      }

      public com.lxd.protobuf.msg.resp.AddFileClientResp.AddFileClientResp_ build() {
        com.lxd.protobuf.msg.resp.AddFileClientResp.AddFileClientResp_ result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.lxd.protobuf.msg.resp.AddFileClientResp.AddFileClientResp_ buildPartial() {
        com.lxd.protobuf.msg.resp.AddFileClientResp.AddFileClientResp_ result = new com.lxd.protobuf.msg.resp.AddFileClientResp.AddFileClientResp_(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.totalBlock_ = totalBlock_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.currentBlock_ = currentBlock_;
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          datas_ = java.util.Collections.unmodifiableList(datas_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.datas_ = datas_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.lxd.protobuf.msg.resp.AddFileClientResp.AddFileClientResp_) {
          return mergeFrom((com.lxd.protobuf.msg.resp.AddFileClientResp.AddFileClientResp_)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.lxd.protobuf.msg.resp.AddFileClientResp.AddFileClientResp_ other) {
        if (other == com.lxd.protobuf.msg.resp.AddFileClientResp.AddFileClientResp_.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasTotalBlock()) {
          setTotalBlock(other.getTotalBlock());
        }
        if (other.hasCurrentBlock()) {
          setCurrentBlock(other.getCurrentBlock());
        }
        if (!other.datas_.isEmpty()) {
          if (datas_.isEmpty()) {
            datas_ = other.datas_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureDatasIsMutable();
            datas_.addAll(other.datas_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        if (!hasTotalBlock()) {
          
          return false;
        }
        if (!hasCurrentBlock()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.lxd.protobuf.msg.resp.AddFileClientResp.AddFileClientResp_ parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.lxd.protobuf.msg.resp.AddFileClientResp.AddFileClientResp_) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 id = 1;
      private int id_ ;
      /**
       * <code>required int32 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      // required int32 total_block = 2;
      private int totalBlock_ ;
      /**
       * <code>required int32 total_block = 2;</code>
       */
      public boolean hasTotalBlock() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 total_block = 2;</code>
       */
      public int getTotalBlock() {
        return totalBlock_;
      }
      /**
       * <code>required int32 total_block = 2;</code>
       */
      public Builder setTotalBlock(int value) {
        bitField0_ |= 0x00000002;
        totalBlock_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 total_block = 2;</code>
       */
      public Builder clearTotalBlock() {
        bitField0_ = (bitField0_ & ~0x00000002);
        totalBlock_ = 0;
        onChanged();
        return this;
      }

      // required int32 current_block = 3;
      private int currentBlock_ ;
      /**
       * <code>required int32 current_block = 3;</code>
       */
      public boolean hasCurrentBlock() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 current_block = 3;</code>
       */
      public int getCurrentBlock() {
        return currentBlock_;
      }
      /**
       * <code>required int32 current_block = 3;</code>
       */
      public Builder setCurrentBlock(int value) {
        bitField0_ |= 0x00000004;
        currentBlock_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 current_block = 3;</code>
       */
      public Builder clearCurrentBlock() {
        bitField0_ = (bitField0_ & ~0x00000004);
        currentBlock_ = 0;
        onChanged();
        return this;
      }

      // repeated bytes datas = 4;
      private java.util.List<com.google.protobuf.ByteString> datas_ = java.util.Collections.emptyList();
      private void ensureDatasIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          datas_ = new java.util.ArrayList<com.google.protobuf.ByteString>(datas_);
          bitField0_ |= 0x00000008;
         }
      }
      /**
       * <code>repeated bytes datas = 4;</code>
       */
      public java.util.List<com.google.protobuf.ByteString>
          getDatasList() {
        return java.util.Collections.unmodifiableList(datas_);
      }
      /**
       * <code>repeated bytes datas = 4;</code>
       */
      public int getDatasCount() {
        return datas_.size();
      }
      /**
       * <code>repeated bytes datas = 4;</code>
       */
      public com.google.protobuf.ByteString getDatas(int index) {
        return datas_.get(index);
      }
      /**
       * <code>repeated bytes datas = 4;</code>
       */
      public Builder setDatas(
          int index, com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureDatasIsMutable();
        datas_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes datas = 4;</code>
       */
      public Builder addDatas(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureDatasIsMutable();
        datas_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes datas = 4;</code>
       */
      public Builder addAllDatas(
          java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
        ensureDatasIsMutable();
        super.addAll(values, datas_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes datas = 4;</code>
       */
      public Builder clearDatas() {
        datas_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:AddFileClientResp_)
    }

    static {
      defaultInstance = new AddFileClientResp_(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:AddFileClientResp_)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_AddFileClientResp__descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_AddFileClientResp__fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027AddFileClientResp.proto\"[\n\022AddFileClie" +
      "ntResp_\022\n\n\002id\030\001 \002(\005\022\023\n\013total_block\030\002 \002(\005" +
      "\022\025\n\rcurrent_block\030\003 \002(\005\022\r\n\005datas\030\004 \003(\014B." +
      "\n\031com.lxd.protobuf.msg.respB\021AddFileClie" +
      "ntResp"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_AddFileClientResp__descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_AddFileClientResp__fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_AddFileClientResp__descriptor,
              new java.lang.String[] { "Id", "TotalBlock", "CurrentBlock", "Datas", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
