// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: R_Console.proto

package com.lxd.protobuf.msg.request.console;

public final class Console {
  private Console() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface Console_OrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional .msg.request.console.AddFile_ addFile = 1;
    /**
     * <code>optional .msg.request.console.AddFile_ addFile = 1;</code>
     *
     * <pre>
     *&#47;&lt; 新增文件
     * </pre>
     */
    boolean hasAddFile();
    /**
     * <code>optional .msg.request.console.AddFile_ addFile = 1;</code>
     *
     * <pre>
     *&#47;&lt; 新增文件
     * </pre>
     */
    com.lxd.protobuf.msg.request.console.AddFile.AddFile_ getAddFile();
    /**
     * <code>optional .msg.request.console.AddFile_ addFile = 1;</code>
     *
     * <pre>
     *&#47;&lt; 新增文件
     * </pre>
     */
    com.lxd.protobuf.msg.request.console.AddFile.AddFile_OrBuilder getAddFileOrBuilder();

    // optional .msg.request.console.UpdateFile_ updateFile = 2;
    /**
     * <code>optional .msg.request.console.UpdateFile_ updateFile = 2;</code>
     *
     * <pre>
     *&#47;&lt; 修改文件
     * </pre>
     */
    boolean hasUpdateFile();
    /**
     * <code>optional .msg.request.console.UpdateFile_ updateFile = 2;</code>
     *
     * <pre>
     *&#47;&lt; 修改文件
     * </pre>
     */
    com.lxd.protobuf.msg.request.console.UpdateFile.UpdateFile_ getUpdateFile();
    /**
     * <code>optional .msg.request.console.UpdateFile_ updateFile = 2;</code>
     *
     * <pre>
     *&#47;&lt; 修改文件
     * </pre>
     */
    com.lxd.protobuf.msg.request.console.UpdateFile.UpdateFile_OrBuilder getUpdateFileOrBuilder();

    // optional .msg.request.console.DeleteFile_ deleteFile = 3;
    /**
     * <code>optional .msg.request.console.DeleteFile_ deleteFile = 3;</code>
     *
     * <pre>
     *&#47;&lt; 删除文件
     * </pre>
     */
    boolean hasDeleteFile();
    /**
     * <code>optional .msg.request.console.DeleteFile_ deleteFile = 3;</code>
     *
     * <pre>
     *&#47;&lt; 删除文件
     * </pre>
     */
    com.lxd.protobuf.msg.request.console.DeleteFile.DeleteFile_ getDeleteFile();
    /**
     * <code>optional .msg.request.console.DeleteFile_ deleteFile = 3;</code>
     *
     * <pre>
     *&#47;&lt; 删除文件
     * </pre>
     */
    com.lxd.protobuf.msg.request.console.DeleteFile.DeleteFile_OrBuilder getDeleteFileOrBuilder();

    // optional .msg.request.console.DownloadFile_ downloadFile = 4;
    /**
     * <code>optional .msg.request.console.DownloadFile_ downloadFile = 4;</code>
     *
     * <pre>
     *&#47;&lt; 下载文件
     * </pre>
     */
    boolean hasDownloadFile();
    /**
     * <code>optional .msg.request.console.DownloadFile_ downloadFile = 4;</code>
     *
     * <pre>
     *&#47;&lt; 下载文件
     * </pre>
     */
    com.lxd.protobuf.msg.request.console.DownloadFile.DownloadFile_ getDownloadFile();
    /**
     * <code>optional .msg.request.console.DownloadFile_ downloadFile = 4;</code>
     *
     * <pre>
     *&#47;&lt; 下载文件
     * </pre>
     */
    com.lxd.protobuf.msg.request.console.DownloadFile.DownloadFile_OrBuilder getDownloadFileOrBuilder();

    // optional .msg.request.console.SyncFile_ syncFile = 5;
    /**
     * <code>optional .msg.request.console.SyncFile_ syncFile = 5;</code>
     *
     * <pre>
     *&#47;&lt; 同步文件信息
     * </pre>
     */
    boolean hasSyncFile();
    /**
     * <code>optional .msg.request.console.SyncFile_ syncFile = 5;</code>
     *
     * <pre>
     *&#47;&lt; 同步文件信息
     * </pre>
     */
    com.lxd.protobuf.msg.request.console.SyncFile.SyncFile_ getSyncFile();
    /**
     * <code>optional .msg.request.console.SyncFile_ syncFile = 5;</code>
     *
     * <pre>
     *&#47;&lt; 同步文件信息
     * </pre>
     */
    com.lxd.protobuf.msg.request.console.SyncFile.SyncFile_OrBuilder getSyncFileOrBuilder();

    // required string user_name = 6;
    /**
     * <code>required string user_name = 6;</code>
     *
     * <pre>
     *&#47;&lt; 用户编号
     * </pre>
     */
    boolean hasUserName();
    /**
     * <code>required string user_name = 6;</code>
     *
     * <pre>
     *&#47;&lt; 用户编号
     * </pre>
     */
    java.lang.String getUserName();
    /**
     * <code>required string user_name = 6;</code>
     *
     * <pre>
     *&#47;&lt; 用户编号
     * </pre>
     */
    com.google.protobuf.ByteString
        getUserNameBytes();
  }
  /**
   * Protobuf type {@code msg.request.console.Console_}
   */
  public static final class Console_ extends
      com.google.protobuf.GeneratedMessage
      implements Console_OrBuilder {
    // Use Console_.newBuilder() to construct.
    private Console_(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Console_(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Console_ defaultInstance;
    public static Console_ getDefaultInstance() {
      return defaultInstance;
    }

    public Console_ getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Console_(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.lxd.protobuf.msg.request.console.AddFile.AddFile_.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = addFile_.toBuilder();
              }
              addFile_ = input.readMessage(com.lxd.protobuf.msg.request.console.AddFile.AddFile_.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(addFile_);
                addFile_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 18: {
              com.lxd.protobuf.msg.request.console.UpdateFile.UpdateFile_.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = updateFile_.toBuilder();
              }
              updateFile_ = input.readMessage(com.lxd.protobuf.msg.request.console.UpdateFile.UpdateFile_.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(updateFile_);
                updateFile_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
            case 26: {
              com.lxd.protobuf.msg.request.console.DeleteFile.DeleteFile_.Builder subBuilder = null;
              if (((bitField0_ & 0x00000004) == 0x00000004)) {
                subBuilder = deleteFile_.toBuilder();
              }
              deleteFile_ = input.readMessage(com.lxd.protobuf.msg.request.console.DeleteFile.DeleteFile_.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(deleteFile_);
                deleteFile_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000004;
              break;
            }
            case 34: {
              com.lxd.protobuf.msg.request.console.DownloadFile.DownloadFile_.Builder subBuilder = null;
              if (((bitField0_ & 0x00000008) == 0x00000008)) {
                subBuilder = downloadFile_.toBuilder();
              }
              downloadFile_ = input.readMessage(com.lxd.protobuf.msg.request.console.DownloadFile.DownloadFile_.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(downloadFile_);
                downloadFile_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000008;
              break;
            }
            case 42: {
              com.lxd.protobuf.msg.request.console.SyncFile.SyncFile_.Builder subBuilder = null;
              if (((bitField0_ & 0x00000010) == 0x00000010)) {
                subBuilder = syncFile_.toBuilder();
              }
              syncFile_ = input.readMessage(com.lxd.protobuf.msg.request.console.SyncFile.SyncFile_.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(syncFile_);
                syncFile_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000010;
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              userName_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.lxd.protobuf.msg.request.console.Console.internal_static_msg_request_console_Console__descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lxd.protobuf.msg.request.console.Console.internal_static_msg_request_console_Console__fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.lxd.protobuf.msg.request.console.Console.Console_.class, com.lxd.protobuf.msg.request.console.Console.Console_.Builder.class);
    }

    public static com.google.protobuf.Parser<Console_> PARSER =
        new com.google.protobuf.AbstractParser<Console_>() {
      public Console_ parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Console_(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Console_> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional .msg.request.console.AddFile_ addFile = 1;
    public static final int ADDFILE_FIELD_NUMBER = 1;
    private com.lxd.protobuf.msg.request.console.AddFile.AddFile_ addFile_;
    /**
     * <code>optional .msg.request.console.AddFile_ addFile = 1;</code>
     *
     * <pre>
     *&#47;&lt; 新增文件
     * </pre>
     */
    public boolean hasAddFile() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .msg.request.console.AddFile_ addFile = 1;</code>
     *
     * <pre>
     *&#47;&lt; 新增文件
     * </pre>
     */
    public com.lxd.protobuf.msg.request.console.AddFile.AddFile_ getAddFile() {
      return addFile_;
    }
    /**
     * <code>optional .msg.request.console.AddFile_ addFile = 1;</code>
     *
     * <pre>
     *&#47;&lt; 新增文件
     * </pre>
     */
    public com.lxd.protobuf.msg.request.console.AddFile.AddFile_OrBuilder getAddFileOrBuilder() {
      return addFile_;
    }

    // optional .msg.request.console.UpdateFile_ updateFile = 2;
    public static final int UPDATEFILE_FIELD_NUMBER = 2;
    private com.lxd.protobuf.msg.request.console.UpdateFile.UpdateFile_ updateFile_;
    /**
     * <code>optional .msg.request.console.UpdateFile_ updateFile = 2;</code>
     *
     * <pre>
     *&#47;&lt; 修改文件
     * </pre>
     */
    public boolean hasUpdateFile() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .msg.request.console.UpdateFile_ updateFile = 2;</code>
     *
     * <pre>
     *&#47;&lt; 修改文件
     * </pre>
     */
    public com.lxd.protobuf.msg.request.console.UpdateFile.UpdateFile_ getUpdateFile() {
      return updateFile_;
    }
    /**
     * <code>optional .msg.request.console.UpdateFile_ updateFile = 2;</code>
     *
     * <pre>
     *&#47;&lt; 修改文件
     * </pre>
     */
    public com.lxd.protobuf.msg.request.console.UpdateFile.UpdateFile_OrBuilder getUpdateFileOrBuilder() {
      return updateFile_;
    }

    // optional .msg.request.console.DeleteFile_ deleteFile = 3;
    public static final int DELETEFILE_FIELD_NUMBER = 3;
    private com.lxd.protobuf.msg.request.console.DeleteFile.DeleteFile_ deleteFile_;
    /**
     * <code>optional .msg.request.console.DeleteFile_ deleteFile = 3;</code>
     *
     * <pre>
     *&#47;&lt; 删除文件
     * </pre>
     */
    public boolean hasDeleteFile() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional .msg.request.console.DeleteFile_ deleteFile = 3;</code>
     *
     * <pre>
     *&#47;&lt; 删除文件
     * </pre>
     */
    public com.lxd.protobuf.msg.request.console.DeleteFile.DeleteFile_ getDeleteFile() {
      return deleteFile_;
    }
    /**
     * <code>optional .msg.request.console.DeleteFile_ deleteFile = 3;</code>
     *
     * <pre>
     *&#47;&lt; 删除文件
     * </pre>
     */
    public com.lxd.protobuf.msg.request.console.DeleteFile.DeleteFile_OrBuilder getDeleteFileOrBuilder() {
      return deleteFile_;
    }

    // optional .msg.request.console.DownloadFile_ downloadFile = 4;
    public static final int DOWNLOADFILE_FIELD_NUMBER = 4;
    private com.lxd.protobuf.msg.request.console.DownloadFile.DownloadFile_ downloadFile_;
    /**
     * <code>optional .msg.request.console.DownloadFile_ downloadFile = 4;</code>
     *
     * <pre>
     *&#47;&lt; 下载文件
     * </pre>
     */
    public boolean hasDownloadFile() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional .msg.request.console.DownloadFile_ downloadFile = 4;</code>
     *
     * <pre>
     *&#47;&lt; 下载文件
     * </pre>
     */
    public com.lxd.protobuf.msg.request.console.DownloadFile.DownloadFile_ getDownloadFile() {
      return downloadFile_;
    }
    /**
     * <code>optional .msg.request.console.DownloadFile_ downloadFile = 4;</code>
     *
     * <pre>
     *&#47;&lt; 下载文件
     * </pre>
     */
    public com.lxd.protobuf.msg.request.console.DownloadFile.DownloadFile_OrBuilder getDownloadFileOrBuilder() {
      return downloadFile_;
    }

    // optional .msg.request.console.SyncFile_ syncFile = 5;
    public static final int SYNCFILE_FIELD_NUMBER = 5;
    private com.lxd.protobuf.msg.request.console.SyncFile.SyncFile_ syncFile_;
    /**
     * <code>optional .msg.request.console.SyncFile_ syncFile = 5;</code>
     *
     * <pre>
     *&#47;&lt; 同步文件信息
     * </pre>
     */
    public boolean hasSyncFile() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional .msg.request.console.SyncFile_ syncFile = 5;</code>
     *
     * <pre>
     *&#47;&lt; 同步文件信息
     * </pre>
     */
    public com.lxd.protobuf.msg.request.console.SyncFile.SyncFile_ getSyncFile() {
      return syncFile_;
    }
    /**
     * <code>optional .msg.request.console.SyncFile_ syncFile = 5;</code>
     *
     * <pre>
     *&#47;&lt; 同步文件信息
     * </pre>
     */
    public com.lxd.protobuf.msg.request.console.SyncFile.SyncFile_OrBuilder getSyncFileOrBuilder() {
      return syncFile_;
    }

    // required string user_name = 6;
    public static final int USER_NAME_FIELD_NUMBER = 6;
    private java.lang.Object userName_;
    /**
     * <code>required string user_name = 6;</code>
     *
     * <pre>
     *&#47;&lt; 用户编号
     * </pre>
     */
    public boolean hasUserName() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required string user_name = 6;</code>
     *
     * <pre>
     *&#47;&lt; 用户编号
     * </pre>
     */
    public java.lang.String getUserName() {
      java.lang.Object ref = userName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          userName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string user_name = 6;</code>
     *
     * <pre>
     *&#47;&lt; 用户编号
     * </pre>
     */
    public com.google.protobuf.ByteString
        getUserNameBytes() {
      java.lang.Object ref = userName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      addFile_ = com.lxd.protobuf.msg.request.console.AddFile.AddFile_.getDefaultInstance();
      updateFile_ = com.lxd.protobuf.msg.request.console.UpdateFile.UpdateFile_.getDefaultInstance();
      deleteFile_ = com.lxd.protobuf.msg.request.console.DeleteFile.DeleteFile_.getDefaultInstance();
      downloadFile_ = com.lxd.protobuf.msg.request.console.DownloadFile.DownloadFile_.getDefaultInstance();
      syncFile_ = com.lxd.protobuf.msg.request.console.SyncFile.SyncFile_.getDefaultInstance();
      userName_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasUserName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasAddFile()) {
        if (!getAddFile().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasUpdateFile()) {
        if (!getUpdateFile().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasDeleteFile()) {
        if (!getDeleteFile().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasDownloadFile()) {
        if (!getDownloadFile().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, addFile_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, updateFile_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(3, deleteFile_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeMessage(4, downloadFile_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeMessage(5, syncFile_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getUserNameBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, addFile_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, updateFile_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, deleteFile_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, downloadFile_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, syncFile_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getUserNameBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.lxd.protobuf.msg.request.console.Console.Console_ parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lxd.protobuf.msg.request.console.Console.Console_ parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lxd.protobuf.msg.request.console.Console.Console_ parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lxd.protobuf.msg.request.console.Console.Console_ parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lxd.protobuf.msg.request.console.Console.Console_ parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.lxd.protobuf.msg.request.console.Console.Console_ parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.lxd.protobuf.msg.request.console.Console.Console_ parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.lxd.protobuf.msg.request.console.Console.Console_ parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.lxd.protobuf.msg.request.console.Console.Console_ parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.lxd.protobuf.msg.request.console.Console.Console_ parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.lxd.protobuf.msg.request.console.Console.Console_ prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code msg.request.console.Console_}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.lxd.protobuf.msg.request.console.Console.Console_OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.lxd.protobuf.msg.request.console.Console.internal_static_msg_request_console_Console__descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.lxd.protobuf.msg.request.console.Console.internal_static_msg_request_console_Console__fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.lxd.protobuf.msg.request.console.Console.Console_.class, com.lxd.protobuf.msg.request.console.Console.Console_.Builder.class);
      }

      // Construct using com.lxd.protobuf.msg.request.console.Console.Console_.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getAddFileFieldBuilder();
          getUpdateFileFieldBuilder();
          getDeleteFileFieldBuilder();
          getDownloadFileFieldBuilder();
          getSyncFileFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (addFileBuilder_ == null) {
          addFile_ = com.lxd.protobuf.msg.request.console.AddFile.AddFile_.getDefaultInstance();
        } else {
          addFileBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        if (updateFileBuilder_ == null) {
          updateFile_ = com.lxd.protobuf.msg.request.console.UpdateFile.UpdateFile_.getDefaultInstance();
        } else {
          updateFileBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        if (deleteFileBuilder_ == null) {
          deleteFile_ = com.lxd.protobuf.msg.request.console.DeleteFile.DeleteFile_.getDefaultInstance();
        } else {
          deleteFileBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        if (downloadFileBuilder_ == null) {
          downloadFile_ = com.lxd.protobuf.msg.request.console.DownloadFile.DownloadFile_.getDefaultInstance();
        } else {
          downloadFileBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        if (syncFileBuilder_ == null) {
          syncFile_ = com.lxd.protobuf.msg.request.console.SyncFile.SyncFile_.getDefaultInstance();
        } else {
          syncFileBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000010);
        userName_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.lxd.protobuf.msg.request.console.Console.internal_static_msg_request_console_Console__descriptor;
      }

      public com.lxd.protobuf.msg.request.console.Console.Console_ getDefaultInstanceForType() {
        return com.lxd.protobuf.msg.request.console.Console.Console_.getDefaultInstance();
      }

      public com.lxd.protobuf.msg.request.console.Console.Console_ build() {
        com.lxd.protobuf.msg.request.console.Console.Console_ result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.lxd.protobuf.msg.request.console.Console.Console_ buildPartial() {
        com.lxd.protobuf.msg.request.console.Console.Console_ result = new com.lxd.protobuf.msg.request.console.Console.Console_(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (addFileBuilder_ == null) {
          result.addFile_ = addFile_;
        } else {
          result.addFile_ = addFileBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (updateFileBuilder_ == null) {
          result.updateFile_ = updateFile_;
        } else {
          result.updateFile_ = updateFileBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (deleteFileBuilder_ == null) {
          result.deleteFile_ = deleteFile_;
        } else {
          result.deleteFile_ = deleteFileBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        if (downloadFileBuilder_ == null) {
          result.downloadFile_ = downloadFile_;
        } else {
          result.downloadFile_ = downloadFileBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        if (syncFileBuilder_ == null) {
          result.syncFile_ = syncFile_;
        } else {
          result.syncFile_ = syncFileBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.userName_ = userName_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.lxd.protobuf.msg.request.console.Console.Console_) {
          return mergeFrom((com.lxd.protobuf.msg.request.console.Console.Console_)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.lxd.protobuf.msg.request.console.Console.Console_ other) {
        if (other == com.lxd.protobuf.msg.request.console.Console.Console_.getDefaultInstance()) return this;
        if (other.hasAddFile()) {
          mergeAddFile(other.getAddFile());
        }
        if (other.hasUpdateFile()) {
          mergeUpdateFile(other.getUpdateFile());
        }
        if (other.hasDeleteFile()) {
          mergeDeleteFile(other.getDeleteFile());
        }
        if (other.hasDownloadFile()) {
          mergeDownloadFile(other.getDownloadFile());
        }
        if (other.hasSyncFile()) {
          mergeSyncFile(other.getSyncFile());
        }
        if (other.hasUserName()) {
          bitField0_ |= 0x00000020;
          userName_ = other.userName_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasUserName()) {
          
          return false;
        }
        if (hasAddFile()) {
          if (!getAddFile().isInitialized()) {
            
            return false;
          }
        }
        if (hasUpdateFile()) {
          if (!getUpdateFile().isInitialized()) {
            
            return false;
          }
        }
        if (hasDeleteFile()) {
          if (!getDeleteFile().isInitialized()) {
            
            return false;
          }
        }
        if (hasDownloadFile()) {
          if (!getDownloadFile().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.lxd.protobuf.msg.request.console.Console.Console_ parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.lxd.protobuf.msg.request.console.Console.Console_) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional .msg.request.console.AddFile_ addFile = 1;
      private com.lxd.protobuf.msg.request.console.AddFile.AddFile_ addFile_ = com.lxd.protobuf.msg.request.console.AddFile.AddFile_.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.lxd.protobuf.msg.request.console.AddFile.AddFile_, com.lxd.protobuf.msg.request.console.AddFile.AddFile_.Builder, com.lxd.protobuf.msg.request.console.AddFile.AddFile_OrBuilder> addFileBuilder_;
      /**
       * <code>optional .msg.request.console.AddFile_ addFile = 1;</code>
       *
       * <pre>
       *&#47;&lt; 新增文件
       * </pre>
       */
      public boolean hasAddFile() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .msg.request.console.AddFile_ addFile = 1;</code>
       *
       * <pre>
       *&#47;&lt; 新增文件
       * </pre>
       */
      public com.lxd.protobuf.msg.request.console.AddFile.AddFile_ getAddFile() {
        if (addFileBuilder_ == null) {
          return addFile_;
        } else {
          return addFileBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .msg.request.console.AddFile_ addFile = 1;</code>
       *
       * <pre>
       *&#47;&lt; 新增文件
       * </pre>
       */
      public Builder setAddFile(com.lxd.protobuf.msg.request.console.AddFile.AddFile_ value) {
        if (addFileBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          addFile_ = value;
          onChanged();
        } else {
          addFileBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .msg.request.console.AddFile_ addFile = 1;</code>
       *
       * <pre>
       *&#47;&lt; 新增文件
       * </pre>
       */
      public Builder setAddFile(
          com.lxd.protobuf.msg.request.console.AddFile.AddFile_.Builder builderForValue) {
        if (addFileBuilder_ == null) {
          addFile_ = builderForValue.build();
          onChanged();
        } else {
          addFileBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .msg.request.console.AddFile_ addFile = 1;</code>
       *
       * <pre>
       *&#47;&lt; 新增文件
       * </pre>
       */
      public Builder mergeAddFile(com.lxd.protobuf.msg.request.console.AddFile.AddFile_ value) {
        if (addFileBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              addFile_ != com.lxd.protobuf.msg.request.console.AddFile.AddFile_.getDefaultInstance()) {
            addFile_ =
              com.lxd.protobuf.msg.request.console.AddFile.AddFile_.newBuilder(addFile_).mergeFrom(value).buildPartial();
          } else {
            addFile_ = value;
          }
          onChanged();
        } else {
          addFileBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .msg.request.console.AddFile_ addFile = 1;</code>
       *
       * <pre>
       *&#47;&lt; 新增文件
       * </pre>
       */
      public Builder clearAddFile() {
        if (addFileBuilder_ == null) {
          addFile_ = com.lxd.protobuf.msg.request.console.AddFile.AddFile_.getDefaultInstance();
          onChanged();
        } else {
          addFileBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>optional .msg.request.console.AddFile_ addFile = 1;</code>
       *
       * <pre>
       *&#47;&lt; 新增文件
       * </pre>
       */
      public com.lxd.protobuf.msg.request.console.AddFile.AddFile_.Builder getAddFileBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getAddFileFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .msg.request.console.AddFile_ addFile = 1;</code>
       *
       * <pre>
       *&#47;&lt; 新增文件
       * </pre>
       */
      public com.lxd.protobuf.msg.request.console.AddFile.AddFile_OrBuilder getAddFileOrBuilder() {
        if (addFileBuilder_ != null) {
          return addFileBuilder_.getMessageOrBuilder();
        } else {
          return addFile_;
        }
      }
      /**
       * <code>optional .msg.request.console.AddFile_ addFile = 1;</code>
       *
       * <pre>
       *&#47;&lt; 新增文件
       * </pre>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.lxd.protobuf.msg.request.console.AddFile.AddFile_, com.lxd.protobuf.msg.request.console.AddFile.AddFile_.Builder, com.lxd.protobuf.msg.request.console.AddFile.AddFile_OrBuilder> 
          getAddFileFieldBuilder() {
        if (addFileBuilder_ == null) {
          addFileBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.lxd.protobuf.msg.request.console.AddFile.AddFile_, com.lxd.protobuf.msg.request.console.AddFile.AddFile_.Builder, com.lxd.protobuf.msg.request.console.AddFile.AddFile_OrBuilder>(
                  addFile_,
                  getParentForChildren(),
                  isClean());
          addFile_ = null;
        }
        return addFileBuilder_;
      }

      // optional .msg.request.console.UpdateFile_ updateFile = 2;
      private com.lxd.protobuf.msg.request.console.UpdateFile.UpdateFile_ updateFile_ = com.lxd.protobuf.msg.request.console.UpdateFile.UpdateFile_.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.lxd.protobuf.msg.request.console.UpdateFile.UpdateFile_, com.lxd.protobuf.msg.request.console.UpdateFile.UpdateFile_.Builder, com.lxd.protobuf.msg.request.console.UpdateFile.UpdateFile_OrBuilder> updateFileBuilder_;
      /**
       * <code>optional .msg.request.console.UpdateFile_ updateFile = 2;</code>
       *
       * <pre>
       *&#47;&lt; 修改文件
       * </pre>
       */
      public boolean hasUpdateFile() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .msg.request.console.UpdateFile_ updateFile = 2;</code>
       *
       * <pre>
       *&#47;&lt; 修改文件
       * </pre>
       */
      public com.lxd.protobuf.msg.request.console.UpdateFile.UpdateFile_ getUpdateFile() {
        if (updateFileBuilder_ == null) {
          return updateFile_;
        } else {
          return updateFileBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .msg.request.console.UpdateFile_ updateFile = 2;</code>
       *
       * <pre>
       *&#47;&lt; 修改文件
       * </pre>
       */
      public Builder setUpdateFile(com.lxd.protobuf.msg.request.console.UpdateFile.UpdateFile_ value) {
        if (updateFileBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          updateFile_ = value;
          onChanged();
        } else {
          updateFileBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .msg.request.console.UpdateFile_ updateFile = 2;</code>
       *
       * <pre>
       *&#47;&lt; 修改文件
       * </pre>
       */
      public Builder setUpdateFile(
          com.lxd.protobuf.msg.request.console.UpdateFile.UpdateFile_.Builder builderForValue) {
        if (updateFileBuilder_ == null) {
          updateFile_ = builderForValue.build();
          onChanged();
        } else {
          updateFileBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .msg.request.console.UpdateFile_ updateFile = 2;</code>
       *
       * <pre>
       *&#47;&lt; 修改文件
       * </pre>
       */
      public Builder mergeUpdateFile(com.lxd.protobuf.msg.request.console.UpdateFile.UpdateFile_ value) {
        if (updateFileBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              updateFile_ != com.lxd.protobuf.msg.request.console.UpdateFile.UpdateFile_.getDefaultInstance()) {
            updateFile_ =
              com.lxd.protobuf.msg.request.console.UpdateFile.UpdateFile_.newBuilder(updateFile_).mergeFrom(value).buildPartial();
          } else {
            updateFile_ = value;
          }
          onChanged();
        } else {
          updateFileBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .msg.request.console.UpdateFile_ updateFile = 2;</code>
       *
       * <pre>
       *&#47;&lt; 修改文件
       * </pre>
       */
      public Builder clearUpdateFile() {
        if (updateFileBuilder_ == null) {
          updateFile_ = com.lxd.protobuf.msg.request.console.UpdateFile.UpdateFile_.getDefaultInstance();
          onChanged();
        } else {
          updateFileBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>optional .msg.request.console.UpdateFile_ updateFile = 2;</code>
       *
       * <pre>
       *&#47;&lt; 修改文件
       * </pre>
       */
      public com.lxd.protobuf.msg.request.console.UpdateFile.UpdateFile_.Builder getUpdateFileBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getUpdateFileFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .msg.request.console.UpdateFile_ updateFile = 2;</code>
       *
       * <pre>
       *&#47;&lt; 修改文件
       * </pre>
       */
      public com.lxd.protobuf.msg.request.console.UpdateFile.UpdateFile_OrBuilder getUpdateFileOrBuilder() {
        if (updateFileBuilder_ != null) {
          return updateFileBuilder_.getMessageOrBuilder();
        } else {
          return updateFile_;
        }
      }
      /**
       * <code>optional .msg.request.console.UpdateFile_ updateFile = 2;</code>
       *
       * <pre>
       *&#47;&lt; 修改文件
       * </pre>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.lxd.protobuf.msg.request.console.UpdateFile.UpdateFile_, com.lxd.protobuf.msg.request.console.UpdateFile.UpdateFile_.Builder, com.lxd.protobuf.msg.request.console.UpdateFile.UpdateFile_OrBuilder> 
          getUpdateFileFieldBuilder() {
        if (updateFileBuilder_ == null) {
          updateFileBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.lxd.protobuf.msg.request.console.UpdateFile.UpdateFile_, com.lxd.protobuf.msg.request.console.UpdateFile.UpdateFile_.Builder, com.lxd.protobuf.msg.request.console.UpdateFile.UpdateFile_OrBuilder>(
                  updateFile_,
                  getParentForChildren(),
                  isClean());
          updateFile_ = null;
        }
        return updateFileBuilder_;
      }

      // optional .msg.request.console.DeleteFile_ deleteFile = 3;
      private com.lxd.protobuf.msg.request.console.DeleteFile.DeleteFile_ deleteFile_ = com.lxd.protobuf.msg.request.console.DeleteFile.DeleteFile_.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.lxd.protobuf.msg.request.console.DeleteFile.DeleteFile_, com.lxd.protobuf.msg.request.console.DeleteFile.DeleteFile_.Builder, com.lxd.protobuf.msg.request.console.DeleteFile.DeleteFile_OrBuilder> deleteFileBuilder_;
      /**
       * <code>optional .msg.request.console.DeleteFile_ deleteFile = 3;</code>
       *
       * <pre>
       *&#47;&lt; 删除文件
       * </pre>
       */
      public boolean hasDeleteFile() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional .msg.request.console.DeleteFile_ deleteFile = 3;</code>
       *
       * <pre>
       *&#47;&lt; 删除文件
       * </pre>
       */
      public com.lxd.protobuf.msg.request.console.DeleteFile.DeleteFile_ getDeleteFile() {
        if (deleteFileBuilder_ == null) {
          return deleteFile_;
        } else {
          return deleteFileBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .msg.request.console.DeleteFile_ deleteFile = 3;</code>
       *
       * <pre>
       *&#47;&lt; 删除文件
       * </pre>
       */
      public Builder setDeleteFile(com.lxd.protobuf.msg.request.console.DeleteFile.DeleteFile_ value) {
        if (deleteFileBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          deleteFile_ = value;
          onChanged();
        } else {
          deleteFileBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .msg.request.console.DeleteFile_ deleteFile = 3;</code>
       *
       * <pre>
       *&#47;&lt; 删除文件
       * </pre>
       */
      public Builder setDeleteFile(
          com.lxd.protobuf.msg.request.console.DeleteFile.DeleteFile_.Builder builderForValue) {
        if (deleteFileBuilder_ == null) {
          deleteFile_ = builderForValue.build();
          onChanged();
        } else {
          deleteFileBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .msg.request.console.DeleteFile_ deleteFile = 3;</code>
       *
       * <pre>
       *&#47;&lt; 删除文件
       * </pre>
       */
      public Builder mergeDeleteFile(com.lxd.protobuf.msg.request.console.DeleteFile.DeleteFile_ value) {
        if (deleteFileBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              deleteFile_ != com.lxd.protobuf.msg.request.console.DeleteFile.DeleteFile_.getDefaultInstance()) {
            deleteFile_ =
              com.lxd.protobuf.msg.request.console.DeleteFile.DeleteFile_.newBuilder(deleteFile_).mergeFrom(value).buildPartial();
          } else {
            deleteFile_ = value;
          }
          onChanged();
        } else {
          deleteFileBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .msg.request.console.DeleteFile_ deleteFile = 3;</code>
       *
       * <pre>
       *&#47;&lt; 删除文件
       * </pre>
       */
      public Builder clearDeleteFile() {
        if (deleteFileBuilder_ == null) {
          deleteFile_ = com.lxd.protobuf.msg.request.console.DeleteFile.DeleteFile_.getDefaultInstance();
          onChanged();
        } else {
          deleteFileBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      /**
       * <code>optional .msg.request.console.DeleteFile_ deleteFile = 3;</code>
       *
       * <pre>
       *&#47;&lt; 删除文件
       * </pre>
       */
      public com.lxd.protobuf.msg.request.console.DeleteFile.DeleteFile_.Builder getDeleteFileBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getDeleteFileFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .msg.request.console.DeleteFile_ deleteFile = 3;</code>
       *
       * <pre>
       *&#47;&lt; 删除文件
       * </pre>
       */
      public com.lxd.protobuf.msg.request.console.DeleteFile.DeleteFile_OrBuilder getDeleteFileOrBuilder() {
        if (deleteFileBuilder_ != null) {
          return deleteFileBuilder_.getMessageOrBuilder();
        } else {
          return deleteFile_;
        }
      }
      /**
       * <code>optional .msg.request.console.DeleteFile_ deleteFile = 3;</code>
       *
       * <pre>
       *&#47;&lt; 删除文件
       * </pre>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.lxd.protobuf.msg.request.console.DeleteFile.DeleteFile_, com.lxd.protobuf.msg.request.console.DeleteFile.DeleteFile_.Builder, com.lxd.protobuf.msg.request.console.DeleteFile.DeleteFile_OrBuilder> 
          getDeleteFileFieldBuilder() {
        if (deleteFileBuilder_ == null) {
          deleteFileBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.lxd.protobuf.msg.request.console.DeleteFile.DeleteFile_, com.lxd.protobuf.msg.request.console.DeleteFile.DeleteFile_.Builder, com.lxd.protobuf.msg.request.console.DeleteFile.DeleteFile_OrBuilder>(
                  deleteFile_,
                  getParentForChildren(),
                  isClean());
          deleteFile_ = null;
        }
        return deleteFileBuilder_;
      }

      // optional .msg.request.console.DownloadFile_ downloadFile = 4;
      private com.lxd.protobuf.msg.request.console.DownloadFile.DownloadFile_ downloadFile_ = com.lxd.protobuf.msg.request.console.DownloadFile.DownloadFile_.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.lxd.protobuf.msg.request.console.DownloadFile.DownloadFile_, com.lxd.protobuf.msg.request.console.DownloadFile.DownloadFile_.Builder, com.lxd.protobuf.msg.request.console.DownloadFile.DownloadFile_OrBuilder> downloadFileBuilder_;
      /**
       * <code>optional .msg.request.console.DownloadFile_ downloadFile = 4;</code>
       *
       * <pre>
       *&#47;&lt; 下载文件
       * </pre>
       */
      public boolean hasDownloadFile() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional .msg.request.console.DownloadFile_ downloadFile = 4;</code>
       *
       * <pre>
       *&#47;&lt; 下载文件
       * </pre>
       */
      public com.lxd.protobuf.msg.request.console.DownloadFile.DownloadFile_ getDownloadFile() {
        if (downloadFileBuilder_ == null) {
          return downloadFile_;
        } else {
          return downloadFileBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .msg.request.console.DownloadFile_ downloadFile = 4;</code>
       *
       * <pre>
       *&#47;&lt; 下载文件
       * </pre>
       */
      public Builder setDownloadFile(com.lxd.protobuf.msg.request.console.DownloadFile.DownloadFile_ value) {
        if (downloadFileBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          downloadFile_ = value;
          onChanged();
        } else {
          downloadFileBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .msg.request.console.DownloadFile_ downloadFile = 4;</code>
       *
       * <pre>
       *&#47;&lt; 下载文件
       * </pre>
       */
      public Builder setDownloadFile(
          com.lxd.protobuf.msg.request.console.DownloadFile.DownloadFile_.Builder builderForValue) {
        if (downloadFileBuilder_ == null) {
          downloadFile_ = builderForValue.build();
          onChanged();
        } else {
          downloadFileBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .msg.request.console.DownloadFile_ downloadFile = 4;</code>
       *
       * <pre>
       *&#47;&lt; 下载文件
       * </pre>
       */
      public Builder mergeDownloadFile(com.lxd.protobuf.msg.request.console.DownloadFile.DownloadFile_ value) {
        if (downloadFileBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008) &&
              downloadFile_ != com.lxd.protobuf.msg.request.console.DownloadFile.DownloadFile_.getDefaultInstance()) {
            downloadFile_ =
              com.lxd.protobuf.msg.request.console.DownloadFile.DownloadFile_.newBuilder(downloadFile_).mergeFrom(value).buildPartial();
          } else {
            downloadFile_ = value;
          }
          onChanged();
        } else {
          downloadFileBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .msg.request.console.DownloadFile_ downloadFile = 4;</code>
       *
       * <pre>
       *&#47;&lt; 下载文件
       * </pre>
       */
      public Builder clearDownloadFile() {
        if (downloadFileBuilder_ == null) {
          downloadFile_ = com.lxd.protobuf.msg.request.console.DownloadFile.DownloadFile_.getDefaultInstance();
          onChanged();
        } else {
          downloadFileBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      /**
       * <code>optional .msg.request.console.DownloadFile_ downloadFile = 4;</code>
       *
       * <pre>
       *&#47;&lt; 下载文件
       * </pre>
       */
      public com.lxd.protobuf.msg.request.console.DownloadFile.DownloadFile_.Builder getDownloadFileBuilder() {
        bitField0_ |= 0x00000008;
        onChanged();
        return getDownloadFileFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .msg.request.console.DownloadFile_ downloadFile = 4;</code>
       *
       * <pre>
       *&#47;&lt; 下载文件
       * </pre>
       */
      public com.lxd.protobuf.msg.request.console.DownloadFile.DownloadFile_OrBuilder getDownloadFileOrBuilder() {
        if (downloadFileBuilder_ != null) {
          return downloadFileBuilder_.getMessageOrBuilder();
        } else {
          return downloadFile_;
        }
      }
      /**
       * <code>optional .msg.request.console.DownloadFile_ downloadFile = 4;</code>
       *
       * <pre>
       *&#47;&lt; 下载文件
       * </pre>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.lxd.protobuf.msg.request.console.DownloadFile.DownloadFile_, com.lxd.protobuf.msg.request.console.DownloadFile.DownloadFile_.Builder, com.lxd.protobuf.msg.request.console.DownloadFile.DownloadFile_OrBuilder> 
          getDownloadFileFieldBuilder() {
        if (downloadFileBuilder_ == null) {
          downloadFileBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.lxd.protobuf.msg.request.console.DownloadFile.DownloadFile_, com.lxd.protobuf.msg.request.console.DownloadFile.DownloadFile_.Builder, com.lxd.protobuf.msg.request.console.DownloadFile.DownloadFile_OrBuilder>(
                  downloadFile_,
                  getParentForChildren(),
                  isClean());
          downloadFile_ = null;
        }
        return downloadFileBuilder_;
      }

      // optional .msg.request.console.SyncFile_ syncFile = 5;
      private com.lxd.protobuf.msg.request.console.SyncFile.SyncFile_ syncFile_ = com.lxd.protobuf.msg.request.console.SyncFile.SyncFile_.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.lxd.protobuf.msg.request.console.SyncFile.SyncFile_, com.lxd.protobuf.msg.request.console.SyncFile.SyncFile_.Builder, com.lxd.protobuf.msg.request.console.SyncFile.SyncFile_OrBuilder> syncFileBuilder_;
      /**
       * <code>optional .msg.request.console.SyncFile_ syncFile = 5;</code>
       *
       * <pre>
       *&#47;&lt; 同步文件信息
       * </pre>
       */
      public boolean hasSyncFile() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional .msg.request.console.SyncFile_ syncFile = 5;</code>
       *
       * <pre>
       *&#47;&lt; 同步文件信息
       * </pre>
       */
      public com.lxd.protobuf.msg.request.console.SyncFile.SyncFile_ getSyncFile() {
        if (syncFileBuilder_ == null) {
          return syncFile_;
        } else {
          return syncFileBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .msg.request.console.SyncFile_ syncFile = 5;</code>
       *
       * <pre>
       *&#47;&lt; 同步文件信息
       * </pre>
       */
      public Builder setSyncFile(com.lxd.protobuf.msg.request.console.SyncFile.SyncFile_ value) {
        if (syncFileBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          syncFile_ = value;
          onChanged();
        } else {
          syncFileBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>optional .msg.request.console.SyncFile_ syncFile = 5;</code>
       *
       * <pre>
       *&#47;&lt; 同步文件信息
       * </pre>
       */
      public Builder setSyncFile(
          com.lxd.protobuf.msg.request.console.SyncFile.SyncFile_.Builder builderForValue) {
        if (syncFileBuilder_ == null) {
          syncFile_ = builderForValue.build();
          onChanged();
        } else {
          syncFileBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>optional .msg.request.console.SyncFile_ syncFile = 5;</code>
       *
       * <pre>
       *&#47;&lt; 同步文件信息
       * </pre>
       */
      public Builder mergeSyncFile(com.lxd.protobuf.msg.request.console.SyncFile.SyncFile_ value) {
        if (syncFileBuilder_ == null) {
          if (((bitField0_ & 0x00000010) == 0x00000010) &&
              syncFile_ != com.lxd.protobuf.msg.request.console.SyncFile.SyncFile_.getDefaultInstance()) {
            syncFile_ =
              com.lxd.protobuf.msg.request.console.SyncFile.SyncFile_.newBuilder(syncFile_).mergeFrom(value).buildPartial();
          } else {
            syncFile_ = value;
          }
          onChanged();
        } else {
          syncFileBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>optional .msg.request.console.SyncFile_ syncFile = 5;</code>
       *
       * <pre>
       *&#47;&lt; 同步文件信息
       * </pre>
       */
      public Builder clearSyncFile() {
        if (syncFileBuilder_ == null) {
          syncFile_ = com.lxd.protobuf.msg.request.console.SyncFile.SyncFile_.getDefaultInstance();
          onChanged();
        } else {
          syncFileBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }
      /**
       * <code>optional .msg.request.console.SyncFile_ syncFile = 5;</code>
       *
       * <pre>
       *&#47;&lt; 同步文件信息
       * </pre>
       */
      public com.lxd.protobuf.msg.request.console.SyncFile.SyncFile_.Builder getSyncFileBuilder() {
        bitField0_ |= 0x00000010;
        onChanged();
        return getSyncFileFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .msg.request.console.SyncFile_ syncFile = 5;</code>
       *
       * <pre>
       *&#47;&lt; 同步文件信息
       * </pre>
       */
      public com.lxd.protobuf.msg.request.console.SyncFile.SyncFile_OrBuilder getSyncFileOrBuilder() {
        if (syncFileBuilder_ != null) {
          return syncFileBuilder_.getMessageOrBuilder();
        } else {
          return syncFile_;
        }
      }
      /**
       * <code>optional .msg.request.console.SyncFile_ syncFile = 5;</code>
       *
       * <pre>
       *&#47;&lt; 同步文件信息
       * </pre>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.lxd.protobuf.msg.request.console.SyncFile.SyncFile_, com.lxd.protobuf.msg.request.console.SyncFile.SyncFile_.Builder, com.lxd.protobuf.msg.request.console.SyncFile.SyncFile_OrBuilder> 
          getSyncFileFieldBuilder() {
        if (syncFileBuilder_ == null) {
          syncFileBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.lxd.protobuf.msg.request.console.SyncFile.SyncFile_, com.lxd.protobuf.msg.request.console.SyncFile.SyncFile_.Builder, com.lxd.protobuf.msg.request.console.SyncFile.SyncFile_OrBuilder>(
                  syncFile_,
                  getParentForChildren(),
                  isClean());
          syncFile_ = null;
        }
        return syncFileBuilder_;
      }

      // required string user_name = 6;
      private java.lang.Object userName_ = "";
      /**
       * <code>required string user_name = 6;</code>
       *
       * <pre>
       *&#47;&lt; 用户编号
       * </pre>
       */
      public boolean hasUserName() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required string user_name = 6;</code>
       *
       * <pre>
       *&#47;&lt; 用户编号
       * </pre>
       */
      public java.lang.String getUserName() {
        java.lang.Object ref = userName_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          userName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string user_name = 6;</code>
       *
       * <pre>
       *&#47;&lt; 用户编号
       * </pre>
       */
      public com.google.protobuf.ByteString
          getUserNameBytes() {
        java.lang.Object ref = userName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string user_name = 6;</code>
       *
       * <pre>
       *&#47;&lt; 用户编号
       * </pre>
       */
      public Builder setUserName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        userName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string user_name = 6;</code>
       *
       * <pre>
       *&#47;&lt; 用户编号
       * </pre>
       */
      public Builder clearUserName() {
        bitField0_ = (bitField0_ & ~0x00000020);
        userName_ = getDefaultInstance().getUserName();
        onChanged();
        return this;
      }
      /**
       * <code>required string user_name = 6;</code>
       *
       * <pre>
       *&#47;&lt; 用户编号
       * </pre>
       */
      public Builder setUserNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        userName_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:msg.request.console.Console_)
    }

    static {
      defaultInstance = new Console_(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:msg.request.console.Console_)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_msg_request_console_Console__descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_msg_request_console_Console__fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017R_Console.proto\022\023msg.request.console\032\021" +
      "R_C_AddFile.proto\032\024R_C_UpdateFile.proto\032" +
      "\024R_C_DeleteFile.proto\032\026R_C_DownloadFile." +
      "proto\032\022R_C_SyncFile.proto\"\245\002\n\010Console_\022." +
      "\n\007addFile\030\001 \001(\0132\035.msg.request.console.Ad" +
      "dFile_\0224\n\nupdateFile\030\002 \001(\0132 .msg.request" +
      ".console.UpdateFile_\0224\n\ndeleteFile\030\003 \001(\013" +
      "2 .msg.request.console.DeleteFile_\0228\n\014do" +
      "wnloadFile\030\004 \001(\0132\".msg.request.console.D" +
      "ownloadFile_\0220\n\010syncFile\030\005 \001(\0132\036.msg.req",
      "uest.console.SyncFile_\022\021\n\tuser_name\030\006 \002(" +
      "\tB/\n$com.lxd.protobuf.msg.request.consol" +
      "eB\007Console"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_msg_request_console_Console__descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_msg_request_console_Console__fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_msg_request_console_Console__descriptor,
              new java.lang.String[] { "AddFile", "UpdateFile", "DeleteFile", "DownloadFile", "SyncFile", "UserName", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.lxd.protobuf.msg.request.console.AddFile.getDescriptor(),
          com.lxd.protobuf.msg.request.console.UpdateFile.getDescriptor(),
          com.lxd.protobuf.msg.request.console.DeleteFile.getDescriptor(),
          com.lxd.protobuf.msg.request.console.DownloadFile.getDescriptor(),
          com.lxd.protobuf.msg.request.console.SyncFile.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
