// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: R_C_MotionSync.proto

package com.lxd.protobuf.msg.request.console;

public final class MotionSync {
  private MotionSync() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface MotionSync_OrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated .msg.request.console.MotionSync_.File files = 1;
    /**
     * <code>repeated .msg.request.console.MotionSync_.File files = 1;</code>
     *
     * <pre>
     *&#47;&lt; 文件信息链表
     * </pre>
     */
    java.util.List<com.lxd.protobuf.msg.request.console.MotionSync.MotionSync_.File> 
        getFilesList();
    /**
     * <code>repeated .msg.request.console.MotionSync_.File files = 1;</code>
     *
     * <pre>
     *&#47;&lt; 文件信息链表
     * </pre>
     */
    com.lxd.protobuf.msg.request.console.MotionSync.MotionSync_.File getFiles(int index);
    /**
     * <code>repeated .msg.request.console.MotionSync_.File files = 1;</code>
     *
     * <pre>
     *&#47;&lt; 文件信息链表
     * </pre>
     */
    int getFilesCount();
    /**
     * <code>repeated .msg.request.console.MotionSync_.File files = 1;</code>
     *
     * <pre>
     *&#47;&lt; 文件信息链表
     * </pre>
     */
    java.util.List<? extends com.lxd.protobuf.msg.request.console.MotionSync.MotionSync_.FileOrBuilder> 
        getFilesOrBuilderList();
    /**
     * <code>repeated .msg.request.console.MotionSync_.File files = 1;</code>
     *
     * <pre>
     *&#47;&lt; 文件信息链表
     * </pre>
     */
    com.lxd.protobuf.msg.request.console.MotionSync.MotionSync_.FileOrBuilder getFilesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code msg.request.console.MotionSync_}
   *
   * <pre>
   *&#47;&lt; 同步请求
   * </pre>
   */
  public static final class MotionSync_ extends
      com.google.protobuf.GeneratedMessage
      implements MotionSync_OrBuilder {
    // Use MotionSync_.newBuilder() to construct.
    private MotionSync_(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private MotionSync_(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final MotionSync_ defaultInstance;
    public static MotionSync_ getDefaultInstance() {
      return defaultInstance;
    }

    public MotionSync_ getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private MotionSync_(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                files_ = new java.util.ArrayList<com.lxd.protobuf.msg.request.console.MotionSync.MotionSync_.File>();
                mutable_bitField0_ |= 0x00000001;
              }
              files_.add(input.readMessage(com.lxd.protobuf.msg.request.console.MotionSync.MotionSync_.File.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          files_ = java.util.Collections.unmodifiableList(files_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.lxd.protobuf.msg.request.console.MotionSync.internal_static_msg_request_console_MotionSync__descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lxd.protobuf.msg.request.console.MotionSync.internal_static_msg_request_console_MotionSync__fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.lxd.protobuf.msg.request.console.MotionSync.MotionSync_.class, com.lxd.protobuf.msg.request.console.MotionSync.MotionSync_.Builder.class);
    }

    public static com.google.protobuf.Parser<MotionSync_> PARSER =
        new com.google.protobuf.AbstractParser<MotionSync_>() {
      public MotionSync_ parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MotionSync_(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<MotionSync_> getParserForType() {
      return PARSER;
    }

    public interface FileOrBuilder
        extends com.google.protobuf.MessageOrBuilder {

      // required string path = 1;
      /**
       * <code>required string path = 1;</code>
       *
       * <pre>
       *&#47;/&lt; 文件路径
       * </pre>
       */
      boolean hasPath();
      /**
       * <code>required string path = 1;</code>
       *
       * <pre>
       *&#47;/&lt; 文件路径
       * </pre>
       */
      java.lang.String getPath();
      /**
       * <code>required string path = 1;</code>
       *
       * <pre>
       *&#47;/&lt; 文件路径
       * </pre>
       */
      com.google.protobuf.ByteString
          getPathBytes();

      // required int64 last = 2;
      /**
       * <code>required int64 last = 2;</code>
       *
       * <pre>
       *&#47;&lt; 文件最后修改时间
       * </pre>
       */
      boolean hasLast();
      /**
       * <code>required int64 last = 2;</code>
       *
       * <pre>
       *&#47;&lt; 文件最后修改时间
       * </pre>
       */
      long getLast();
    }
    /**
     * Protobuf type {@code msg.request.console.MotionSync_.File}
     *
     * <pre>
     *&#47;&lt; 文件信息消息
     * </pre>
     */
    public static final class File extends
        com.google.protobuf.GeneratedMessage
        implements FileOrBuilder {
      // Use File.newBuilder() to construct.
      private File(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private File(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final File defaultInstance;
      public static File getDefaultInstance() {
        return defaultInstance;
      }

      public File getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private File(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                bitField0_ |= 0x00000001;
                path_ = input.readBytes();
                break;
              }
              case 16: {
                bitField0_ |= 0x00000002;
                last_ = input.readInt64();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.lxd.protobuf.msg.request.console.MotionSync.internal_static_msg_request_console_MotionSync__File_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.lxd.protobuf.msg.request.console.MotionSync.internal_static_msg_request_console_MotionSync__File_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.lxd.protobuf.msg.request.console.MotionSync.MotionSync_.File.class, com.lxd.protobuf.msg.request.console.MotionSync.MotionSync_.File.Builder.class);
      }

      public static com.google.protobuf.Parser<File> PARSER =
          new com.google.protobuf.AbstractParser<File>() {
        public File parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new File(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<File> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      // required string path = 1;
      public static final int PATH_FIELD_NUMBER = 1;
      private java.lang.Object path_;
      /**
       * <code>required string path = 1;</code>
       *
       * <pre>
       *&#47;/&lt; 文件路径
       * </pre>
       */
      public boolean hasPath() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string path = 1;</code>
       *
       * <pre>
       *&#47;/&lt; 文件路径
       * </pre>
       */
      public java.lang.String getPath() {
        java.lang.Object ref = path_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            path_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string path = 1;</code>
       *
       * <pre>
       *&#47;/&lt; 文件路径
       * </pre>
       */
      public com.google.protobuf.ByteString
          getPathBytes() {
        java.lang.Object ref = path_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          path_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      // required int64 last = 2;
      public static final int LAST_FIELD_NUMBER = 2;
      private long last_;
      /**
       * <code>required int64 last = 2;</code>
       *
       * <pre>
       *&#47;&lt; 文件最后修改时间
       * </pre>
       */
      public boolean hasLast() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int64 last = 2;</code>
       *
       * <pre>
       *&#47;&lt; 文件最后修改时间
       * </pre>
       */
      public long getLast() {
        return last_;
      }

      private void initFields() {
        path_ = "";
        last_ = 0L;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;

        if (!hasPath()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasLast()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, getPathBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeInt64(2, last_);
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, getPathBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt64Size(2, last_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static com.lxd.protobuf.msg.request.console.MotionSync.MotionSync_.File parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.lxd.protobuf.msg.request.console.MotionSync.MotionSync_.File parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.lxd.protobuf.msg.request.console.MotionSync.MotionSync_.File parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.lxd.protobuf.msg.request.console.MotionSync.MotionSync_.File parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.lxd.protobuf.msg.request.console.MotionSync.MotionSync_.File parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.lxd.protobuf.msg.request.console.MotionSync.MotionSync_.File parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static com.lxd.protobuf.msg.request.console.MotionSync.MotionSync_.File parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static com.lxd.protobuf.msg.request.console.MotionSync.MotionSync_.File parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static com.lxd.protobuf.msg.request.console.MotionSync.MotionSync_.File parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.lxd.protobuf.msg.request.console.MotionSync.MotionSync_.File parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(com.lxd.protobuf.msg.request.console.MotionSync.MotionSync_.File prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code msg.request.console.MotionSync_.File}
       *
       * <pre>
       *&#47;&lt; 文件信息消息
       * </pre>
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements com.lxd.protobuf.msg.request.console.MotionSync.MotionSync_.FileOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.lxd.protobuf.msg.request.console.MotionSync.internal_static_msg_request_console_MotionSync__File_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.lxd.protobuf.msg.request.console.MotionSync.internal_static_msg_request_console_MotionSync__File_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.lxd.protobuf.msg.request.console.MotionSync.MotionSync_.File.class, com.lxd.protobuf.msg.request.console.MotionSync.MotionSync_.File.Builder.class);
        }

        // Construct using com.lxd.protobuf.msg.request.console.MotionSync.MotionSync_.File.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          path_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          last_ = 0L;
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.lxd.protobuf.msg.request.console.MotionSync.internal_static_msg_request_console_MotionSync__File_descriptor;
        }

        public com.lxd.protobuf.msg.request.console.MotionSync.MotionSync_.File getDefaultInstanceForType() {
          return com.lxd.protobuf.msg.request.console.MotionSync.MotionSync_.File.getDefaultInstance();
        }

        public com.lxd.protobuf.msg.request.console.MotionSync.MotionSync_.File build() {
          com.lxd.protobuf.msg.request.console.MotionSync.MotionSync_.File result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public com.lxd.protobuf.msg.request.console.MotionSync.MotionSync_.File buildPartial() {
          com.lxd.protobuf.msg.request.console.MotionSync.MotionSync_.File result = new com.lxd.protobuf.msg.request.console.MotionSync.MotionSync_.File(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.path_ = path_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.last_ = last_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.lxd.protobuf.msg.request.console.MotionSync.MotionSync_.File) {
            return mergeFrom((com.lxd.protobuf.msg.request.console.MotionSync.MotionSync_.File)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.lxd.protobuf.msg.request.console.MotionSync.MotionSync_.File other) {
          if (other == com.lxd.protobuf.msg.request.console.MotionSync.MotionSync_.File.getDefaultInstance()) return this;
          if (other.hasPath()) {
            bitField0_ |= 0x00000001;
            path_ = other.path_;
            onChanged();
          }
          if (other.hasLast()) {
            setLast(other.getLast());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasPath()) {
            
            return false;
          }
          if (!hasLast()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.lxd.protobuf.msg.request.console.MotionSync.MotionSync_.File parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.lxd.protobuf.msg.request.console.MotionSync.MotionSync_.File) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        // required string path = 1;
        private java.lang.Object path_ = "";
        /**
         * <code>required string path = 1;</code>
         *
         * <pre>
         *&#47;/&lt; 文件路径
         * </pre>
         */
        public boolean hasPath() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required string path = 1;</code>
         *
         * <pre>
         *&#47;/&lt; 文件路径
         * </pre>
         */
        public java.lang.String getPath() {
          java.lang.Object ref = path_;
          if (!(ref instanceof java.lang.String)) {
            java.lang.String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            path_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string path = 1;</code>
         *
         * <pre>
         *&#47;/&lt; 文件路径
         * </pre>
         */
        public com.google.protobuf.ByteString
            getPathBytes() {
          java.lang.Object ref = path_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            path_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string path = 1;</code>
         *
         * <pre>
         *&#47;/&lt; 文件路径
         * </pre>
         */
        public Builder setPath(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          path_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string path = 1;</code>
         *
         * <pre>
         *&#47;/&lt; 文件路径
         * </pre>
         */
        public Builder clearPath() {
          bitField0_ = (bitField0_ & ~0x00000001);
          path_ = getDefaultInstance().getPath();
          onChanged();
          return this;
        }
        /**
         * <code>required string path = 1;</code>
         *
         * <pre>
         *&#47;/&lt; 文件路径
         * </pre>
         */
        public Builder setPathBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          path_ = value;
          onChanged();
          return this;
        }

        // required int64 last = 2;
        private long last_ ;
        /**
         * <code>required int64 last = 2;</code>
         *
         * <pre>
         *&#47;&lt; 文件最后修改时间
         * </pre>
         */
        public boolean hasLast() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>required int64 last = 2;</code>
         *
         * <pre>
         *&#47;&lt; 文件最后修改时间
         * </pre>
         */
        public long getLast() {
          return last_;
        }
        /**
         * <code>required int64 last = 2;</code>
         *
         * <pre>
         *&#47;&lt; 文件最后修改时间
         * </pre>
         */
        public Builder setLast(long value) {
          bitField0_ |= 0x00000002;
          last_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required int64 last = 2;</code>
         *
         * <pre>
         *&#47;&lt; 文件最后修改时间
         * </pre>
         */
        public Builder clearLast() {
          bitField0_ = (bitField0_ & ~0x00000002);
          last_ = 0L;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:msg.request.console.MotionSync_.File)
      }

      static {
        defaultInstance = new File(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:msg.request.console.MotionSync_.File)
    }

    // repeated .msg.request.console.MotionSync_.File files = 1;
    public static final int FILES_FIELD_NUMBER = 1;
    private java.util.List<com.lxd.protobuf.msg.request.console.MotionSync.MotionSync_.File> files_;
    /**
     * <code>repeated .msg.request.console.MotionSync_.File files = 1;</code>
     *
     * <pre>
     *&#47;&lt; 文件信息链表
     * </pre>
     */
    public java.util.List<com.lxd.protobuf.msg.request.console.MotionSync.MotionSync_.File> getFilesList() {
      return files_;
    }
    /**
     * <code>repeated .msg.request.console.MotionSync_.File files = 1;</code>
     *
     * <pre>
     *&#47;&lt; 文件信息链表
     * </pre>
     */
    public java.util.List<? extends com.lxd.protobuf.msg.request.console.MotionSync.MotionSync_.FileOrBuilder> 
        getFilesOrBuilderList() {
      return files_;
    }
    /**
     * <code>repeated .msg.request.console.MotionSync_.File files = 1;</code>
     *
     * <pre>
     *&#47;&lt; 文件信息链表
     * </pre>
     */
    public int getFilesCount() {
      return files_.size();
    }
    /**
     * <code>repeated .msg.request.console.MotionSync_.File files = 1;</code>
     *
     * <pre>
     *&#47;&lt; 文件信息链表
     * </pre>
     */
    public com.lxd.protobuf.msg.request.console.MotionSync.MotionSync_.File getFiles(int index) {
      return files_.get(index);
    }
    /**
     * <code>repeated .msg.request.console.MotionSync_.File files = 1;</code>
     *
     * <pre>
     *&#47;&lt; 文件信息链表
     * </pre>
     */
    public com.lxd.protobuf.msg.request.console.MotionSync.MotionSync_.FileOrBuilder getFilesOrBuilder(
        int index) {
      return files_.get(index);
    }

    private void initFields() {
      files_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      for (int i = 0; i < getFilesCount(); i++) {
        if (!getFiles(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < files_.size(); i++) {
        output.writeMessage(1, files_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < files_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, files_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.lxd.protobuf.msg.request.console.MotionSync.MotionSync_ parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lxd.protobuf.msg.request.console.MotionSync.MotionSync_ parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lxd.protobuf.msg.request.console.MotionSync.MotionSync_ parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lxd.protobuf.msg.request.console.MotionSync.MotionSync_ parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lxd.protobuf.msg.request.console.MotionSync.MotionSync_ parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.lxd.protobuf.msg.request.console.MotionSync.MotionSync_ parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.lxd.protobuf.msg.request.console.MotionSync.MotionSync_ parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.lxd.protobuf.msg.request.console.MotionSync.MotionSync_ parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.lxd.protobuf.msg.request.console.MotionSync.MotionSync_ parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.lxd.protobuf.msg.request.console.MotionSync.MotionSync_ parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.lxd.protobuf.msg.request.console.MotionSync.MotionSync_ prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code msg.request.console.MotionSync_}
     *
     * <pre>
     *&#47;&lt; 同步请求
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.lxd.protobuf.msg.request.console.MotionSync.MotionSync_OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.lxd.protobuf.msg.request.console.MotionSync.internal_static_msg_request_console_MotionSync__descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.lxd.protobuf.msg.request.console.MotionSync.internal_static_msg_request_console_MotionSync__fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.lxd.protobuf.msg.request.console.MotionSync.MotionSync_.class, com.lxd.protobuf.msg.request.console.MotionSync.MotionSync_.Builder.class);
      }

      // Construct using com.lxd.protobuf.msg.request.console.MotionSync.MotionSync_.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getFilesFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (filesBuilder_ == null) {
          files_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          filesBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.lxd.protobuf.msg.request.console.MotionSync.internal_static_msg_request_console_MotionSync__descriptor;
      }

      public com.lxd.protobuf.msg.request.console.MotionSync.MotionSync_ getDefaultInstanceForType() {
        return com.lxd.protobuf.msg.request.console.MotionSync.MotionSync_.getDefaultInstance();
      }

      public com.lxd.protobuf.msg.request.console.MotionSync.MotionSync_ build() {
        com.lxd.protobuf.msg.request.console.MotionSync.MotionSync_ result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.lxd.protobuf.msg.request.console.MotionSync.MotionSync_ buildPartial() {
        com.lxd.protobuf.msg.request.console.MotionSync.MotionSync_ result = new com.lxd.protobuf.msg.request.console.MotionSync.MotionSync_(this);
        int from_bitField0_ = bitField0_;
        if (filesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            files_ = java.util.Collections.unmodifiableList(files_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.files_ = files_;
        } else {
          result.files_ = filesBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.lxd.protobuf.msg.request.console.MotionSync.MotionSync_) {
          return mergeFrom((com.lxd.protobuf.msg.request.console.MotionSync.MotionSync_)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.lxd.protobuf.msg.request.console.MotionSync.MotionSync_ other) {
        if (other == com.lxd.protobuf.msg.request.console.MotionSync.MotionSync_.getDefaultInstance()) return this;
        if (filesBuilder_ == null) {
          if (!other.files_.isEmpty()) {
            if (files_.isEmpty()) {
              files_ = other.files_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureFilesIsMutable();
              files_.addAll(other.files_);
            }
            onChanged();
          }
        } else {
          if (!other.files_.isEmpty()) {
            if (filesBuilder_.isEmpty()) {
              filesBuilder_.dispose();
              filesBuilder_ = null;
              files_ = other.files_;
              bitField0_ = (bitField0_ & ~0x00000001);
              filesBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getFilesFieldBuilder() : null;
            } else {
              filesBuilder_.addAllMessages(other.files_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getFilesCount(); i++) {
          if (!getFiles(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.lxd.protobuf.msg.request.console.MotionSync.MotionSync_ parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.lxd.protobuf.msg.request.console.MotionSync.MotionSync_) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .msg.request.console.MotionSync_.File files = 1;
      private java.util.List<com.lxd.protobuf.msg.request.console.MotionSync.MotionSync_.File> files_ =
        java.util.Collections.emptyList();
      private void ensureFilesIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          files_ = new java.util.ArrayList<com.lxd.protobuf.msg.request.console.MotionSync.MotionSync_.File>(files_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.lxd.protobuf.msg.request.console.MotionSync.MotionSync_.File, com.lxd.protobuf.msg.request.console.MotionSync.MotionSync_.File.Builder, com.lxd.protobuf.msg.request.console.MotionSync.MotionSync_.FileOrBuilder> filesBuilder_;

      /**
       * <code>repeated .msg.request.console.MotionSync_.File files = 1;</code>
       *
       * <pre>
       *&#47;&lt; 文件信息链表
       * </pre>
       */
      public java.util.List<com.lxd.protobuf.msg.request.console.MotionSync.MotionSync_.File> getFilesList() {
        if (filesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(files_);
        } else {
          return filesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .msg.request.console.MotionSync_.File files = 1;</code>
       *
       * <pre>
       *&#47;&lt; 文件信息链表
       * </pre>
       */
      public int getFilesCount() {
        if (filesBuilder_ == null) {
          return files_.size();
        } else {
          return filesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .msg.request.console.MotionSync_.File files = 1;</code>
       *
       * <pre>
       *&#47;&lt; 文件信息链表
       * </pre>
       */
      public com.lxd.protobuf.msg.request.console.MotionSync.MotionSync_.File getFiles(int index) {
        if (filesBuilder_ == null) {
          return files_.get(index);
        } else {
          return filesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .msg.request.console.MotionSync_.File files = 1;</code>
       *
       * <pre>
       *&#47;&lt; 文件信息链表
       * </pre>
       */
      public Builder setFiles(
          int index, com.lxd.protobuf.msg.request.console.MotionSync.MotionSync_.File value) {
        if (filesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFilesIsMutable();
          files_.set(index, value);
          onChanged();
        } else {
          filesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .msg.request.console.MotionSync_.File files = 1;</code>
       *
       * <pre>
       *&#47;&lt; 文件信息链表
       * </pre>
       */
      public Builder setFiles(
          int index, com.lxd.protobuf.msg.request.console.MotionSync.MotionSync_.File.Builder builderForValue) {
        if (filesBuilder_ == null) {
          ensureFilesIsMutable();
          files_.set(index, builderForValue.build());
          onChanged();
        } else {
          filesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .msg.request.console.MotionSync_.File files = 1;</code>
       *
       * <pre>
       *&#47;&lt; 文件信息链表
       * </pre>
       */
      public Builder addFiles(com.lxd.protobuf.msg.request.console.MotionSync.MotionSync_.File value) {
        if (filesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFilesIsMutable();
          files_.add(value);
          onChanged();
        } else {
          filesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .msg.request.console.MotionSync_.File files = 1;</code>
       *
       * <pre>
       *&#47;&lt; 文件信息链表
       * </pre>
       */
      public Builder addFiles(
          int index, com.lxd.protobuf.msg.request.console.MotionSync.MotionSync_.File value) {
        if (filesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFilesIsMutable();
          files_.add(index, value);
          onChanged();
        } else {
          filesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .msg.request.console.MotionSync_.File files = 1;</code>
       *
       * <pre>
       *&#47;&lt; 文件信息链表
       * </pre>
       */
      public Builder addFiles(
          com.lxd.protobuf.msg.request.console.MotionSync.MotionSync_.File.Builder builderForValue) {
        if (filesBuilder_ == null) {
          ensureFilesIsMutable();
          files_.add(builderForValue.build());
          onChanged();
        } else {
          filesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .msg.request.console.MotionSync_.File files = 1;</code>
       *
       * <pre>
       *&#47;&lt; 文件信息链表
       * </pre>
       */
      public Builder addFiles(
          int index, com.lxd.protobuf.msg.request.console.MotionSync.MotionSync_.File.Builder builderForValue) {
        if (filesBuilder_ == null) {
          ensureFilesIsMutable();
          files_.add(index, builderForValue.build());
          onChanged();
        } else {
          filesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .msg.request.console.MotionSync_.File files = 1;</code>
       *
       * <pre>
       *&#47;&lt; 文件信息链表
       * </pre>
       */
      public Builder addAllFiles(
          java.lang.Iterable<? extends com.lxd.protobuf.msg.request.console.MotionSync.MotionSync_.File> values) {
        if (filesBuilder_ == null) {
          ensureFilesIsMutable();
          super.addAll(values, files_);
          onChanged();
        } else {
          filesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .msg.request.console.MotionSync_.File files = 1;</code>
       *
       * <pre>
       *&#47;&lt; 文件信息链表
       * </pre>
       */
      public Builder clearFiles() {
        if (filesBuilder_ == null) {
          files_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          filesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .msg.request.console.MotionSync_.File files = 1;</code>
       *
       * <pre>
       *&#47;&lt; 文件信息链表
       * </pre>
       */
      public Builder removeFiles(int index) {
        if (filesBuilder_ == null) {
          ensureFilesIsMutable();
          files_.remove(index);
          onChanged();
        } else {
          filesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .msg.request.console.MotionSync_.File files = 1;</code>
       *
       * <pre>
       *&#47;&lt; 文件信息链表
       * </pre>
       */
      public com.lxd.protobuf.msg.request.console.MotionSync.MotionSync_.File.Builder getFilesBuilder(
          int index) {
        return getFilesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .msg.request.console.MotionSync_.File files = 1;</code>
       *
       * <pre>
       *&#47;&lt; 文件信息链表
       * </pre>
       */
      public com.lxd.protobuf.msg.request.console.MotionSync.MotionSync_.FileOrBuilder getFilesOrBuilder(
          int index) {
        if (filesBuilder_ == null) {
          return files_.get(index);  } else {
          return filesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .msg.request.console.MotionSync_.File files = 1;</code>
       *
       * <pre>
       *&#47;&lt; 文件信息链表
       * </pre>
       */
      public java.util.List<? extends com.lxd.protobuf.msg.request.console.MotionSync.MotionSync_.FileOrBuilder> 
           getFilesOrBuilderList() {
        if (filesBuilder_ != null) {
          return filesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(files_);
        }
      }
      /**
       * <code>repeated .msg.request.console.MotionSync_.File files = 1;</code>
       *
       * <pre>
       *&#47;&lt; 文件信息链表
       * </pre>
       */
      public com.lxd.protobuf.msg.request.console.MotionSync.MotionSync_.File.Builder addFilesBuilder() {
        return getFilesFieldBuilder().addBuilder(
            com.lxd.protobuf.msg.request.console.MotionSync.MotionSync_.File.getDefaultInstance());
      }
      /**
       * <code>repeated .msg.request.console.MotionSync_.File files = 1;</code>
       *
       * <pre>
       *&#47;&lt; 文件信息链表
       * </pre>
       */
      public com.lxd.protobuf.msg.request.console.MotionSync.MotionSync_.File.Builder addFilesBuilder(
          int index) {
        return getFilesFieldBuilder().addBuilder(
            index, com.lxd.protobuf.msg.request.console.MotionSync.MotionSync_.File.getDefaultInstance());
      }
      /**
       * <code>repeated .msg.request.console.MotionSync_.File files = 1;</code>
       *
       * <pre>
       *&#47;&lt; 文件信息链表
       * </pre>
       */
      public java.util.List<com.lxd.protobuf.msg.request.console.MotionSync.MotionSync_.File.Builder> 
           getFilesBuilderList() {
        return getFilesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.lxd.protobuf.msg.request.console.MotionSync.MotionSync_.File, com.lxd.protobuf.msg.request.console.MotionSync.MotionSync_.File.Builder, com.lxd.protobuf.msg.request.console.MotionSync.MotionSync_.FileOrBuilder> 
          getFilesFieldBuilder() {
        if (filesBuilder_ == null) {
          filesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.lxd.protobuf.msg.request.console.MotionSync.MotionSync_.File, com.lxd.protobuf.msg.request.console.MotionSync.MotionSync_.File.Builder, com.lxd.protobuf.msg.request.console.MotionSync.MotionSync_.FileOrBuilder>(
                  files_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          files_ = null;
        }
        return filesBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:msg.request.console.MotionSync_)
    }

    static {
      defaultInstance = new MotionSync_(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:msg.request.console.MotionSync_)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_msg_request_console_MotionSync__descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_msg_request_console_MotionSync__fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_msg_request_console_MotionSync__File_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_msg_request_console_MotionSync__File_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024R_C_MotionSync.proto\022\023msg.request.cons" +
      "ole\"g\n\013MotionSync_\0224\n\005files\030\001 \003(\0132%.msg." +
      "request.console.MotionSync_.File\032\"\n\004File" +
      "\022\014\n\004path\030\001 \002(\t\022\014\n\004last\030\002 \002(\003B2\n$com.lxd." +
      "protobuf.msg.request.consoleB\nMotionSync"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_msg_request_console_MotionSync__descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_msg_request_console_MotionSync__fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_msg_request_console_MotionSync__descriptor,
              new java.lang.String[] { "Files", });
          internal_static_msg_request_console_MotionSync__File_descriptor =
            internal_static_msg_request_console_MotionSync__descriptor.getNestedTypes().get(0);
          internal_static_msg_request_console_MotionSync__File_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_msg_request_console_MotionSync__File_descriptor,
              new java.lang.String[] { "Path", "Last", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
