// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: R_C_UpdateFile.proto

package com.lxd.protobuf.msg.request.console;

public final class UpdateFile {
  private UpdateFile() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface UpdateFile_OrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string path = 1;
    /**
     * <code>required string path = 1;</code>
     *
     * <pre>
     *&#47;&lt; 文件路径
     * </pre>
     */
    boolean hasPath();
    /**
     * <code>required string path = 1;</code>
     *
     * <pre>
     *&#47;&lt; 文件路径
     * </pre>
     */
    java.lang.String getPath();
    /**
     * <code>required string path = 1;</code>
     *
     * <pre>
     *&#47;&lt; 文件路径
     * </pre>
     */
    com.google.protobuf.ByteString
        getPathBytes();

    // required string md5 = 2;
    /**
     * <code>required string md5 = 2;</code>
     *
     * <pre>
     *&#47;&lt; 新文件md5
     * </pre>
     */
    boolean hasMd5();
    /**
     * <code>required string md5 = 2;</code>
     *
     * <pre>
     *&#47;&lt; 新文件md5
     * </pre>
     */
    java.lang.String getMd5();
    /**
     * <code>required string md5 = 2;</code>
     *
     * <pre>
     *&#47;&lt; 新文件md5
     * </pre>
     */
    com.google.protobuf.ByteString
        getMd5Bytes();

    // required int64 length = 3;
    /**
     * <code>required int64 length = 3;</code>
     *
     * <pre>
     *&#47;&lt; 新文件长度
     * </pre>
     */
    boolean hasLength();
    /**
     * <code>required int64 length = 3;</code>
     *
     * <pre>
     *&#47;&lt; 新文件长度
     * </pre>
     */
    long getLength();

    // required int64 last = 4;
    /**
     * <code>required int64 last = 4;</code>
     *
     * <pre>
     *&#47;&lt; 新文件最后修改时间
     * </pre>
     */
    boolean hasLast();
    /**
     * <code>required int64 last = 4;</code>
     *
     * <pre>
     *&#47;&lt; 新文件最后修改时间
     * </pre>
     */
    long getLast();

    // required int32 total = 5;
    /**
     * <code>required int32 total = 5;</code>
     *
     * <pre>
     *&#47;&lt; 任务块号
     * </pre>
     */
    boolean hasTotal();
    /**
     * <code>required int32 total = 5;</code>
     *
     * <pre>
     *&#47;&lt; 任务块号
     * </pre>
     */
    int getTotal();
  }
  /**
   * Protobuf type {@code msg.request.console.UpdateFile_}
   */
  public static final class UpdateFile_ extends
      com.google.protobuf.GeneratedMessage
      implements UpdateFile_OrBuilder {
    // Use UpdateFile_.newBuilder() to construct.
    private UpdateFile_(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private UpdateFile_(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final UpdateFile_ defaultInstance;
    public static UpdateFile_ getDefaultInstance() {
      return defaultInstance;
    }

    public UpdateFile_ getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private UpdateFile_(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              path_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              md5_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              length_ = input.readInt64();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              last_ = input.readInt64();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              total_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.lxd.protobuf.msg.request.console.UpdateFile.internal_static_msg_request_console_UpdateFile__descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lxd.protobuf.msg.request.console.UpdateFile.internal_static_msg_request_console_UpdateFile__fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.lxd.protobuf.msg.request.console.UpdateFile.UpdateFile_.class, com.lxd.protobuf.msg.request.console.UpdateFile.UpdateFile_.Builder.class);
    }

    public static com.google.protobuf.Parser<UpdateFile_> PARSER =
        new com.google.protobuf.AbstractParser<UpdateFile_>() {
      public UpdateFile_ parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new UpdateFile_(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<UpdateFile_> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string path = 1;
    public static final int PATH_FIELD_NUMBER = 1;
    private java.lang.Object path_;
    /**
     * <code>required string path = 1;</code>
     *
     * <pre>
     *&#47;&lt; 文件路径
     * </pre>
     */
    public boolean hasPath() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string path = 1;</code>
     *
     * <pre>
     *&#47;&lt; 文件路径
     * </pre>
     */
    public java.lang.String getPath() {
      java.lang.Object ref = path_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          path_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string path = 1;</code>
     *
     * <pre>
     *&#47;&lt; 文件路径
     * </pre>
     */
    public com.google.protobuf.ByteString
        getPathBytes() {
      java.lang.Object ref = path_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        path_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string md5 = 2;
    public static final int MD5_FIELD_NUMBER = 2;
    private java.lang.Object md5_;
    /**
     * <code>required string md5 = 2;</code>
     *
     * <pre>
     *&#47;&lt; 新文件md5
     * </pre>
     */
    public boolean hasMd5() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string md5 = 2;</code>
     *
     * <pre>
     *&#47;&lt; 新文件md5
     * </pre>
     */
    public java.lang.String getMd5() {
      java.lang.Object ref = md5_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          md5_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string md5 = 2;</code>
     *
     * <pre>
     *&#47;&lt; 新文件md5
     * </pre>
     */
    public com.google.protobuf.ByteString
        getMd5Bytes() {
      java.lang.Object ref = md5_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        md5_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required int64 length = 3;
    public static final int LENGTH_FIELD_NUMBER = 3;
    private long length_;
    /**
     * <code>required int64 length = 3;</code>
     *
     * <pre>
     *&#47;&lt; 新文件长度
     * </pre>
     */
    public boolean hasLength() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int64 length = 3;</code>
     *
     * <pre>
     *&#47;&lt; 新文件长度
     * </pre>
     */
    public long getLength() {
      return length_;
    }

    // required int64 last = 4;
    public static final int LAST_FIELD_NUMBER = 4;
    private long last_;
    /**
     * <code>required int64 last = 4;</code>
     *
     * <pre>
     *&#47;&lt; 新文件最后修改时间
     * </pre>
     */
    public boolean hasLast() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required int64 last = 4;</code>
     *
     * <pre>
     *&#47;&lt; 新文件最后修改时间
     * </pre>
     */
    public long getLast() {
      return last_;
    }

    // required int32 total = 5;
    public static final int TOTAL_FIELD_NUMBER = 5;
    private int total_;
    /**
     * <code>required int32 total = 5;</code>
     *
     * <pre>
     *&#47;&lt; 任务块号
     * </pre>
     */
    public boolean hasTotal() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required int32 total = 5;</code>
     *
     * <pre>
     *&#47;&lt; 任务块号
     * </pre>
     */
    public int getTotal() {
      return total_;
    }

    private void initFields() {
      path_ = "";
      md5_ = "";
      length_ = 0L;
      last_ = 0L;
      total_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasPath()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMd5()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLength()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLast()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTotal()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getPathBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getMd5Bytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, length_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt64(4, last_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, total_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getPathBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getMd5Bytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, length_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, last_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, total_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.lxd.protobuf.msg.request.console.UpdateFile.UpdateFile_ parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lxd.protobuf.msg.request.console.UpdateFile.UpdateFile_ parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lxd.protobuf.msg.request.console.UpdateFile.UpdateFile_ parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lxd.protobuf.msg.request.console.UpdateFile.UpdateFile_ parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lxd.protobuf.msg.request.console.UpdateFile.UpdateFile_ parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.lxd.protobuf.msg.request.console.UpdateFile.UpdateFile_ parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.lxd.protobuf.msg.request.console.UpdateFile.UpdateFile_ parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.lxd.protobuf.msg.request.console.UpdateFile.UpdateFile_ parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.lxd.protobuf.msg.request.console.UpdateFile.UpdateFile_ parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.lxd.protobuf.msg.request.console.UpdateFile.UpdateFile_ parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.lxd.protobuf.msg.request.console.UpdateFile.UpdateFile_ prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code msg.request.console.UpdateFile_}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.lxd.protobuf.msg.request.console.UpdateFile.UpdateFile_OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.lxd.protobuf.msg.request.console.UpdateFile.internal_static_msg_request_console_UpdateFile__descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.lxd.protobuf.msg.request.console.UpdateFile.internal_static_msg_request_console_UpdateFile__fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.lxd.protobuf.msg.request.console.UpdateFile.UpdateFile_.class, com.lxd.protobuf.msg.request.console.UpdateFile.UpdateFile_.Builder.class);
      }

      // Construct using com.lxd.protobuf.msg.request.console.UpdateFile.UpdateFile_.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        path_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        md5_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        length_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        last_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        total_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.lxd.protobuf.msg.request.console.UpdateFile.internal_static_msg_request_console_UpdateFile__descriptor;
      }

      public com.lxd.protobuf.msg.request.console.UpdateFile.UpdateFile_ getDefaultInstanceForType() {
        return com.lxd.protobuf.msg.request.console.UpdateFile.UpdateFile_.getDefaultInstance();
      }

      public com.lxd.protobuf.msg.request.console.UpdateFile.UpdateFile_ build() {
        com.lxd.protobuf.msg.request.console.UpdateFile.UpdateFile_ result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.lxd.protobuf.msg.request.console.UpdateFile.UpdateFile_ buildPartial() {
        com.lxd.protobuf.msg.request.console.UpdateFile.UpdateFile_ result = new com.lxd.protobuf.msg.request.console.UpdateFile.UpdateFile_(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.path_ = path_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.md5_ = md5_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.length_ = length_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.last_ = last_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.total_ = total_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.lxd.protobuf.msg.request.console.UpdateFile.UpdateFile_) {
          return mergeFrom((com.lxd.protobuf.msg.request.console.UpdateFile.UpdateFile_)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.lxd.protobuf.msg.request.console.UpdateFile.UpdateFile_ other) {
        if (other == com.lxd.protobuf.msg.request.console.UpdateFile.UpdateFile_.getDefaultInstance()) return this;
        if (other.hasPath()) {
          bitField0_ |= 0x00000001;
          path_ = other.path_;
          onChanged();
        }
        if (other.hasMd5()) {
          bitField0_ |= 0x00000002;
          md5_ = other.md5_;
          onChanged();
        }
        if (other.hasLength()) {
          setLength(other.getLength());
        }
        if (other.hasLast()) {
          setLast(other.getLast());
        }
        if (other.hasTotal()) {
          setTotal(other.getTotal());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasPath()) {
          
          return false;
        }
        if (!hasMd5()) {
          
          return false;
        }
        if (!hasLength()) {
          
          return false;
        }
        if (!hasLast()) {
          
          return false;
        }
        if (!hasTotal()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.lxd.protobuf.msg.request.console.UpdateFile.UpdateFile_ parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.lxd.protobuf.msg.request.console.UpdateFile.UpdateFile_) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string path = 1;
      private java.lang.Object path_ = "";
      /**
       * <code>required string path = 1;</code>
       *
       * <pre>
       *&#47;&lt; 文件路径
       * </pre>
       */
      public boolean hasPath() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string path = 1;</code>
       *
       * <pre>
       *&#47;&lt; 文件路径
       * </pre>
       */
      public java.lang.String getPath() {
        java.lang.Object ref = path_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          path_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string path = 1;</code>
       *
       * <pre>
       *&#47;&lt; 文件路径
       * </pre>
       */
      public com.google.protobuf.ByteString
          getPathBytes() {
        java.lang.Object ref = path_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          path_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string path = 1;</code>
       *
       * <pre>
       *&#47;&lt; 文件路径
       * </pre>
       */
      public Builder setPath(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        path_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string path = 1;</code>
       *
       * <pre>
       *&#47;&lt; 文件路径
       * </pre>
       */
      public Builder clearPath() {
        bitField0_ = (bitField0_ & ~0x00000001);
        path_ = getDefaultInstance().getPath();
        onChanged();
        return this;
      }
      /**
       * <code>required string path = 1;</code>
       *
       * <pre>
       *&#47;&lt; 文件路径
       * </pre>
       */
      public Builder setPathBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        path_ = value;
        onChanged();
        return this;
      }

      // required string md5 = 2;
      private java.lang.Object md5_ = "";
      /**
       * <code>required string md5 = 2;</code>
       *
       * <pre>
       *&#47;&lt; 新文件md5
       * </pre>
       */
      public boolean hasMd5() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string md5 = 2;</code>
       *
       * <pre>
       *&#47;&lt; 新文件md5
       * </pre>
       */
      public java.lang.String getMd5() {
        java.lang.Object ref = md5_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          md5_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string md5 = 2;</code>
       *
       * <pre>
       *&#47;&lt; 新文件md5
       * </pre>
       */
      public com.google.protobuf.ByteString
          getMd5Bytes() {
        java.lang.Object ref = md5_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          md5_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string md5 = 2;</code>
       *
       * <pre>
       *&#47;&lt; 新文件md5
       * </pre>
       */
      public Builder setMd5(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        md5_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string md5 = 2;</code>
       *
       * <pre>
       *&#47;&lt; 新文件md5
       * </pre>
       */
      public Builder clearMd5() {
        bitField0_ = (bitField0_ & ~0x00000002);
        md5_ = getDefaultInstance().getMd5();
        onChanged();
        return this;
      }
      /**
       * <code>required string md5 = 2;</code>
       *
       * <pre>
       *&#47;&lt; 新文件md5
       * </pre>
       */
      public Builder setMd5Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        md5_ = value;
        onChanged();
        return this;
      }

      // required int64 length = 3;
      private long length_ ;
      /**
       * <code>required int64 length = 3;</code>
       *
       * <pre>
       *&#47;&lt; 新文件长度
       * </pre>
       */
      public boolean hasLength() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int64 length = 3;</code>
       *
       * <pre>
       *&#47;&lt; 新文件长度
       * </pre>
       */
      public long getLength() {
        return length_;
      }
      /**
       * <code>required int64 length = 3;</code>
       *
       * <pre>
       *&#47;&lt; 新文件长度
       * </pre>
       */
      public Builder setLength(long value) {
        bitField0_ |= 0x00000004;
        length_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 length = 3;</code>
       *
       * <pre>
       *&#47;&lt; 新文件长度
       * </pre>
       */
      public Builder clearLength() {
        bitField0_ = (bitField0_ & ~0x00000004);
        length_ = 0L;
        onChanged();
        return this;
      }

      // required int64 last = 4;
      private long last_ ;
      /**
       * <code>required int64 last = 4;</code>
       *
       * <pre>
       *&#47;&lt; 新文件最后修改时间
       * </pre>
       */
      public boolean hasLast() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required int64 last = 4;</code>
       *
       * <pre>
       *&#47;&lt; 新文件最后修改时间
       * </pre>
       */
      public long getLast() {
        return last_;
      }
      /**
       * <code>required int64 last = 4;</code>
       *
       * <pre>
       *&#47;&lt; 新文件最后修改时间
       * </pre>
       */
      public Builder setLast(long value) {
        bitField0_ |= 0x00000008;
        last_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 last = 4;</code>
       *
       * <pre>
       *&#47;&lt; 新文件最后修改时间
       * </pre>
       */
      public Builder clearLast() {
        bitField0_ = (bitField0_ & ~0x00000008);
        last_ = 0L;
        onChanged();
        return this;
      }

      // required int32 total = 5;
      private int total_ ;
      /**
       * <code>required int32 total = 5;</code>
       *
       * <pre>
       *&#47;&lt; 任务块号
       * </pre>
       */
      public boolean hasTotal() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required int32 total = 5;</code>
       *
       * <pre>
       *&#47;&lt; 任务块号
       * </pre>
       */
      public int getTotal() {
        return total_;
      }
      /**
       * <code>required int32 total = 5;</code>
       *
       * <pre>
       *&#47;&lt; 任务块号
       * </pre>
       */
      public Builder setTotal(int value) {
        bitField0_ |= 0x00000010;
        total_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 total = 5;</code>
       *
       * <pre>
       *&#47;&lt; 任务块号
       * </pre>
       */
      public Builder clearTotal() {
        bitField0_ = (bitField0_ & ~0x00000010);
        total_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:msg.request.console.UpdateFile_)
    }

    static {
      defaultInstance = new UpdateFile_(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:msg.request.console.UpdateFile_)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_msg_request_console_UpdateFile__descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_msg_request_console_UpdateFile__fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024R_C_UpdateFile.proto\022\023msg.request.cons" +
      "ole\"U\n\013UpdateFile_\022\014\n\004path\030\001 \002(\t\022\013\n\003md5\030" +
      "\002 \002(\t\022\016\n\006length\030\003 \002(\003\022\014\n\004last\030\004 \002(\003\022\r\n\005t" +
      "otal\030\005 \002(\005B2\n$com.lxd.protobuf.msg.reque" +
      "st.consoleB\nUpdateFile"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_msg_request_console_UpdateFile__descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_msg_request_console_UpdateFile__fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_msg_request_console_UpdateFile__descriptor,
              new java.lang.String[] { "Path", "Md5", "Length", "Last", "Total", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
